/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/googlecloudplatform/compute-class-api/api/cloud.google.com/v1"
	cloudgooglecomv1 "github.com/googlecloudplatform/compute-class-api/client/applyconfiguration/cloud.google.com/v1"
	typedcloudgooglecomv1 "github.com/googlecloudplatform/compute-class-api/client/clientset/versioned/typed/cloud.google.com/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeComputeClasses implements ComputeClassInterface
type fakeComputeClasses struct {
	*gentype.FakeClientWithListAndApply[*v1.ComputeClass, *v1.ComputeClassList, *cloudgooglecomv1.ComputeClassApplyConfiguration]
	Fake *FakeCloudV1
}

func newFakeComputeClasses(fake *FakeCloudV1) typedcloudgooglecomv1.ComputeClassInterface {
	return &fakeComputeClasses{
		gentype.NewFakeClientWithListAndApply[*v1.ComputeClass, *v1.ComputeClassList, *cloudgooglecomv1.ComputeClassApplyConfiguration](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("computeclasses"),
			v1.SchemeGroupVersion.WithKind("ComputeClass"),
			func() *v1.ComputeClass { return &v1.ComputeClass{} },
			func() *v1.ComputeClassList { return &v1.ComputeClassList{} },
			func(dst, src *v1.ComputeClassList) { dst.ListMeta = src.ListMeta },
			func(list *v1.ComputeClassList) []*v1.ComputeClass { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.ComputeClassList, items []*v1.ComputeClass) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
