/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/googlecloudplatform/compute-class-api/api/cloud.google.com/v1"
)

// AllocationStrategyDefaultsApplyConfiguration represents an declarative configuration of the AllocationStrategyDefaults type for use
// with apply.
type AllocationStrategyDefaultsApplyConfiguration struct {
	OnDemand  *v1.AllocationStrategy `json:"onDemand,omitempty"`
	Spot      *v1.AllocationStrategy `json:"spot,omitempty"`
	FlexStart *v1.AllocationStrategy `json:"flexStart,omitempty"`
}

// AllocationStrategyDefaultsApplyConfiguration constructs an declarative configuration of the AllocationStrategyDefaults type for use with
// apply.
func AllocationStrategyDefaults() *AllocationStrategyDefaultsApplyConfiguration {
	return &AllocationStrategyDefaultsApplyConfiguration{}
}

// WithOnDemand sets the OnDemand field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OnDemand field is set to the value of the last call.
func (b *AllocationStrategyDefaultsApplyConfiguration) WithOnDemand(value v1.AllocationStrategy) *AllocationStrategyDefaultsApplyConfiguration {
	b.OnDemand = &value
	return b
}

// WithSpot sets the Spot field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spot field is set to the value of the last call.
func (b *AllocationStrategyDefaultsApplyConfiguration) WithSpot(value v1.AllocationStrategy) *AllocationStrategyDefaultsApplyConfiguration {
	b.Spot = &value
	return b
}

// WithFlexStart sets the FlexStart field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FlexStart field is set to the value of the last call.
func (b *AllocationStrategyDefaultsApplyConfiguration) WithFlexStart(value v1.AllocationStrategy) *AllocationStrategyDefaultsApplyConfiguration {
	b.FlexStart = &value
	return b
}
