/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// AutoscalingPolicyApplyConfiguration represents an declarative configuration of the AutoscalingPolicy type for use
// with apply.
type AutoscalingPolicyApplyConfiguration struct {
	ConsolidationDelayMinutes *int `json:"consolidationDelayMinutes,omitempty"`
	ConsolidationThreshold    *int `json:"consolidationThreshold,omitempty"`
	GPUConsolidationThreshold *int `json:"gpuConsolidationThreshold,omitempty"`
}

// AutoscalingPolicyApplyConfiguration constructs an declarative configuration of the AutoscalingPolicy type for use with
// apply.
func AutoscalingPolicy() *AutoscalingPolicyApplyConfiguration {
	return &AutoscalingPolicyApplyConfiguration{}
}

// WithConsolidationDelayMinutes sets the ConsolidationDelayMinutes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConsolidationDelayMinutes field is set to the value of the last call.
func (b *AutoscalingPolicyApplyConfiguration) WithConsolidationDelayMinutes(value int) *AutoscalingPolicyApplyConfiguration {
	b.ConsolidationDelayMinutes = &value
	return b
}

// WithConsolidationThreshold sets the ConsolidationThreshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConsolidationThreshold field is set to the value of the last call.
func (b *AutoscalingPolicyApplyConfiguration) WithConsolidationThreshold(value int) *AutoscalingPolicyApplyConfiguration {
	b.ConsolidationThreshold = &value
	return b
}

// WithGPUConsolidationThreshold sets the GPUConsolidationThreshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GPUConsolidationThreshold field is set to the value of the last call.
func (b *AutoscalingPolicyApplyConfiguration) WithGPUConsolidationThreshold(value int) *AutoscalingPolicyApplyConfiguration {
	b.GPUConsolidationThreshold = &value
	return b
}
