/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// BlockedNodesInfoApplyConfiguration represents a declarative configuration of the BlockedNodesInfo type for use
// with apply.
//
// BlockedNodesInfo describes how many nodes are blocked from being migrated by a single reason.
type BlockedNodesInfoApplyConfiguration struct {
	// Reason identifies why the migration of the reported nodes cannot proceed.
	// Possible values:
	// * NodeNotReady - the node is not ready, so it is not safe to migrate it.
	// * Cordoned - the node was manually marked as unschedulable.
	// * NodeConsolidationDisabled - the node opted out of removal, for example with the
	// "cluster-autoscaler.kubernetes.io/scale-down-disabled" annotation.
	// * NodePoolOperationInProgress - another operation on the node pool is in progress.
	// * MinCapacityReached - removing the node would violate a configured minimum, such as the
	// node pool minimum size or a resource limit.
	// * MaxNodeDisruptionReached - migrating the node would exceed the disruption budget
	// configured in `spec.activeMigration`.
	// * BlockingPods - a pod running on the node prevents it from being drained, for example a
	// pod that is not backed by a controller or that uses local storage.
	// * PodDisruptionBudget - draining the node would violate a PodDisruptionBudget.
	// * ReplacementUnavailable - replacement capacity matching the desired configuration could
	// not be provisioned, so the migration attempt was abandoned. A node still waiting for
	// capacity that is expected to arrive is reported in `migratingNodes` instead.
	// * RecentMigrationFailure - a recent attempt to migrate the node failed and it is backed off.
	// * AtomicGroupBlocked - the node belongs to an atomically scheduled group in which another
	// node is blocked, so the whole group cannot be migrated.
	// * MigrationBlocked - the node cannot be removed for a reason that is not reported more
	// specifically.
	Reason *string `json:"reason,omitempty"`
	// Count represents the number of nodes blocked by this reason. It is always at least 1.
	Count *int `json:"count,omitempty"`
}

// BlockedNodesInfoApplyConfiguration constructs a declarative configuration of the BlockedNodesInfo type for use with
// apply.
func BlockedNodesInfo() *BlockedNodesInfoApplyConfiguration {
	return &BlockedNodesInfoApplyConfiguration{}
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *BlockedNodesInfoApplyConfiguration) WithReason(value string) *BlockedNodesInfoApplyConfiguration {
	b.Reason = &value
	return b
}

// WithCount sets the Count field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Count field is set to the value of the last call.
func (b *BlockedNodesInfoApplyConfiguration) WithCount(value int) *BlockedNodesInfoApplyConfiguration {
	b.Count = &value
	return b
}
