/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
)

// ComputeClassBufferApplyConfiguration represents a declarative configuration of the ComputeClassBuffer type for use
// with apply.
//
// ComputeClassBuffer defines the desired capacity buffer configuration for a specific provisioning strategy.
type ComputeClassBufferApplyConfiguration struct {
	// ProvisioningStrategy identifies the target buffer strategy (e.g., "buffer.x-k8s.io/active-capacity" or "buffer.gke.io/standby-capacity").
	// When omitted or empty, the default provisioning strategy ("buffer.x-k8s.io/active-capacity") is used.
	ProvisioningStrategy *string `json:"provisioningStrategy,omitempty"`
	// Limits defines the total resource request limits for the buffer (e.g., CPU, memory).
	Limits *corev1.ResourceList `json:"limits,omitempty"`
}

// ComputeClassBufferApplyConfiguration constructs a declarative configuration of the ComputeClassBuffer type for use with
// apply.
func ComputeClassBuffer() *ComputeClassBufferApplyConfiguration {
	return &ComputeClassBufferApplyConfiguration{}
}

// WithProvisioningStrategy sets the ProvisioningStrategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProvisioningStrategy field is set to the value of the last call.
func (b *ComputeClassBufferApplyConfiguration) WithProvisioningStrategy(value string) *ComputeClassBufferApplyConfiguration {
	b.ProvisioningStrategy = &value
	return b
}

// WithLimits sets the Limits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Limits field is set to the value of the last call.
func (b *ComputeClassBufferApplyConfiguration) WithLimits(value corev1.ResourceList) *ComputeClassBufferApplyConfiguration {
	b.Limits = &value
	return b
}
