/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ComputeClassSpecApplyConfiguration represents an declarative configuration of the ComputeClassSpec type for use
// with apply.
type ComputeClassSpecApplyConfiguration struct {
	Priorities           []PriorityApplyConfiguration            `json:"priorities,omitempty"`
	NodePoolAutoCreation *NodePoolAutoCreationApplyConfiguration `json:"nodePoolAutoCreation,omitempty"`
	ActiveMigration      *ActiveMigrationApplyConfiguration      `json:"activeMigration,omitempty"`
	WhenUnsatisfiable    *string                                 `json:"whenUnsatisfiable,omitempty"`
}

// ComputeClassSpecApplyConfiguration constructs an declarative configuration of the ComputeClassSpec type for use with
// apply.
func ComputeClassSpec() *ComputeClassSpecApplyConfiguration {
	return &ComputeClassSpecApplyConfiguration{}
}

// WithPriorities adds the given value to the Priorities field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Priorities field.
func (b *ComputeClassSpecApplyConfiguration) WithPriorities(values ...*PriorityApplyConfiguration) *ComputeClassSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPriorities")
		}
		b.Priorities = append(b.Priorities, *values[i])
	}
	return b
}

// WithNodePoolAutoCreation sets the NodePoolAutoCreation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodePoolAutoCreation field is set to the value of the last call.
func (b *ComputeClassSpecApplyConfiguration) WithNodePoolAutoCreation(value *NodePoolAutoCreationApplyConfiguration) *ComputeClassSpecApplyConfiguration {
	b.NodePoolAutoCreation = value
	return b
}

// WithActiveMigration sets the ActiveMigration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActiveMigration field is set to the value of the last call.
func (b *ComputeClassSpecApplyConfiguration) WithActiveMigration(value *ActiveMigrationApplyConfiguration) *ComputeClassSpecApplyConfiguration {
	b.ActiveMigration = value
	return b
}

// WithWhenUnsatisfiable sets the WhenUnsatisfiable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WhenUnsatisfiable field is set to the value of the last call.
func (b *ComputeClassSpecApplyConfiguration) WithWhenUnsatisfiable(value string) *ComputeClassSpecApplyConfiguration {
	b.WhenUnsatisfiable = &value
	return b
}
