/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ComputeClassSpecApplyConfiguration represents a declarative configuration of the ComputeClassSpec type for use
// with apply.
//
// ComputeClassSpec is a specification of provisioning priorities and
// other autoscaling settings.
//
// TDX should only be enabled on C3, C4, A3 and A4 machine families. This is because TDX has specific hardware requirements that are only met by these machine families.
type ComputeClassSpecApplyConfiguration struct {
	// Priorities is a description of user preferences to be
	// used by a given ComputeClass.
	Priorities []PriorityApplyConfiguration `json:"priorities,omitempty"`
	// NodePoolAutoCreation describes the auto provisioning settings for a given
	// ComputeClass.
	NodePoolAutoCreation *NodePoolAutoCreationApplyConfiguration `json:"nodePoolAutoCreation,omitempty"`
	// ActiveMigration describes settings related to active reconciliation of
	// a given ComputeClass.
	ActiveMigration *ActiveMigrationApplyConfiguration `json:"activeMigration,omitempty"`
	// WhenUnsatisfiable describes autoscaler behaviour in case none
	// of the provided priorities is satisfiable.
	// Currently supported values:
	// * ScaleUpAnyway
	// * DoNotScaleUp
	WhenUnsatisfiable *string `json:"whenUnsatisfiable,omitempty"`
	// AutoscalingPolicy describes settings related to active reconciliation of
	// a given ComputeClass.
	AutoscalingPolicy *AutoscalingPolicyApplyConfiguration `json:"autoscalingPolicy,omitempty"`
	// Autopilot describes the autopilot settings for a given ComputeClass.
	Autopilot *AutopilotApplyConfiguration `json:"autopilot,omitempty"`
	// NodePoolConfig defines required node pool configuration. Existing node pools will be matched with the ComputeClass
	// only if their configuration match this field. Auto-provisioned node pools will be created with this configuration.
	NodePoolConfig *NodePoolConfigApplyConfiguration `json:"nodePoolConfig,omitempty"`
	// NodePoolGroup defines required node pool configurations that are shared between a group of node pools.
	// Existing node pools will be matched with the ComputeClass only if their configuration matches this field.
	// Auto-provisioned node pools will be created with this configuration.
	NodePoolGroup *NodePoolGroupApplyConfiguration `json:"nodePoolGroup,omitempty"`
	// PriorityDefaults define the default rules for all priorities if the rule doesn't exist in some priority.
	// Note: PriorityDefaults doesn't apply to priorities with only Nodepools.
	PriorityDefaults *PriorityDefaultsApplyConfiguration `json:"priorityDefaults,omitempty"`
	// Description is an arbitrary string that usually provides guidelines on
	// when this compute class should be used.
	Description *string `json:"description,omitempty"`
	// MinimumCapacity defines declarative minimum node preprovisioning requirements
	// for the entire ComputeClass.
	MinimumCapacity *MinimumCapacityApplyConfiguration `json:"minimumCapacity,omitempty"`
	// AllocationStrategyDefaults define the default allocation strategies for different provisioning models.
	AllocationStrategyDefaults *AllocationStrategyDefaultsApplyConfiguration `json:"allocationStrategyDefaults,omitempty"`
}

// ComputeClassSpecApplyConfiguration constructs a declarative configuration of the ComputeClassSpec type for use with
// apply.
func ComputeClassSpec() *ComputeClassSpecApplyConfiguration {
	return &ComputeClassSpecApplyConfiguration{}
}

// WithPriorities adds the given value to the Priorities field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Priorities field.
func (b *ComputeClassSpecApplyConfiguration) WithPriorities(values ...*PriorityApplyConfiguration) *ComputeClassSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPriorities")
		}
		b.Priorities = append(b.Priorities, *values[i])
	}
	return b
}

// WithNodePoolAutoCreation sets the NodePoolAutoCreation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodePoolAutoCreation field is set to the value of the last call.
func (b *ComputeClassSpecApplyConfiguration) WithNodePoolAutoCreation(value *NodePoolAutoCreationApplyConfiguration) *ComputeClassSpecApplyConfiguration {
	b.NodePoolAutoCreation = value
	return b
}

// WithActiveMigration sets the ActiveMigration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActiveMigration field is set to the value of the last call.
func (b *ComputeClassSpecApplyConfiguration) WithActiveMigration(value *ActiveMigrationApplyConfiguration) *ComputeClassSpecApplyConfiguration {
	b.ActiveMigration = value
	return b
}

// WithWhenUnsatisfiable sets the WhenUnsatisfiable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WhenUnsatisfiable field is set to the value of the last call.
func (b *ComputeClassSpecApplyConfiguration) WithWhenUnsatisfiable(value string) *ComputeClassSpecApplyConfiguration {
	b.WhenUnsatisfiable = &value
	return b
}

// WithAutoscalingPolicy sets the AutoscalingPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutoscalingPolicy field is set to the value of the last call.
func (b *ComputeClassSpecApplyConfiguration) WithAutoscalingPolicy(value *AutoscalingPolicyApplyConfiguration) *ComputeClassSpecApplyConfiguration {
	b.AutoscalingPolicy = value
	return b
}

// WithAutopilot sets the Autopilot field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Autopilot field is set to the value of the last call.
func (b *ComputeClassSpecApplyConfiguration) WithAutopilot(value *AutopilotApplyConfiguration) *ComputeClassSpecApplyConfiguration {
	b.Autopilot = value
	return b
}

// WithNodePoolConfig sets the NodePoolConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodePoolConfig field is set to the value of the last call.
func (b *ComputeClassSpecApplyConfiguration) WithNodePoolConfig(value *NodePoolConfigApplyConfiguration) *ComputeClassSpecApplyConfiguration {
	b.NodePoolConfig = value
	return b
}

// WithNodePoolGroup sets the NodePoolGroup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodePoolGroup field is set to the value of the last call.
func (b *ComputeClassSpecApplyConfiguration) WithNodePoolGroup(value *NodePoolGroupApplyConfiguration) *ComputeClassSpecApplyConfiguration {
	b.NodePoolGroup = value
	return b
}

// WithPriorityDefaults sets the PriorityDefaults field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PriorityDefaults field is set to the value of the last call.
func (b *ComputeClassSpecApplyConfiguration) WithPriorityDefaults(value *PriorityDefaultsApplyConfiguration) *ComputeClassSpecApplyConfiguration {
	b.PriorityDefaults = value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *ComputeClassSpecApplyConfiguration) WithDescription(value string) *ComputeClassSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithMinimumCapacity sets the MinimumCapacity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinimumCapacity field is set to the value of the last call.
func (b *ComputeClassSpecApplyConfiguration) WithMinimumCapacity(value *MinimumCapacityApplyConfiguration) *ComputeClassSpecApplyConfiguration {
	b.MinimumCapacity = value
	return b
}

// WithAllocationStrategyDefaults sets the AllocationStrategyDefaults field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllocationStrategyDefaults field is set to the value of the last call.
func (b *ComputeClassSpecApplyConfiguration) WithAllocationStrategyDefaults(value *AllocationStrategyDefaultsApplyConfiguration) *ComputeClassSpecApplyConfiguration {
	b.AllocationStrategyDefaults = value
	return b
}
