/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ComputeClassStatusApplyConfiguration represents an declarative configuration of the ComputeClassStatus type for use
// with apply.
type ComputeClassStatusApplyConfiguration struct {
	Conditions       []v1.ConditionApplyConfiguration   `json:"conditions,omitempty"`
	PriorityStatuses []PriorityStatusApplyConfiguration `json:"priorityStatuses,omitempty"`
	ResourceInfo     []ResourceInfoApplyConfiguration   `json:"resourceInfo,omitempty"`
}

// ComputeClassStatusApplyConfiguration constructs an declarative configuration of the ComputeClassStatus type for use with
// apply.
func ComputeClassStatus() *ComputeClassStatusApplyConfiguration {
	return &ComputeClassStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ComputeClassStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ComputeClassStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithPriorityStatuses adds the given value to the PriorityStatuses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PriorityStatuses field.
func (b *ComputeClassStatusApplyConfiguration) WithPriorityStatuses(values ...*PriorityStatusApplyConfiguration) *ComputeClassStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPriorityStatuses")
		}
		b.PriorityStatuses = append(b.PriorityStatuses, *values[i])
	}
	return b
}

// WithResourceInfo adds the given value to the ResourceInfo field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ResourceInfo field.
func (b *ComputeClassStatusApplyConfiguration) WithResourceInfo(values ...*ResourceInfoApplyConfiguration) *ComputeClassStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithResourceInfo")
		}
		b.ResourceInfo = append(b.ResourceInfo, *values[i])
	}
	return b
}
