/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ConfigDriftStatusApplyConfiguration represents a declarative configuration of the ConfigDriftStatus type for use
// with apply.
//
// ConfigDriftStatus describes the progress of migrating nodes whose configuration no longer
// matches the configuration desired by this ComputeClass.
//
// Every node belonging to this ComputeClass is counted in exactly one of `currentNodes`,
// `driftedNodes`, `migratingNodes`, or a single entry of `blockedNodes`. Their sum is therefore
// the total number of nodes belonging to this ComputeClass at the `measuredAt` timestamp.
type ConfigDriftStatusApplyConfiguration struct {
	// CurrentNodes represents the number of nodes that match the current ComputeClass
	// configuration. These nodes are fully up-to-date and require no action.
	CurrentNodes *int `json:"currentNodes,omitempty"`
	// DriftedNodes represents the number of nodes that are running on an outdated configuration.
	// These nodes are eligible for migration, but their migration has not started yet, for example
	// because they are waiting for their turn.
	DriftedNodes *int `json:"driftedNodes,omitempty"`
	// MigratingNodes represents the number of nodes that are currently being migrated. This
	// includes nodes waiting for replacement capacity to be provisioned, as well as nodes that
	// are already cordoned, being drained, or being deleted.
	//
	// A node waiting for replacement capacity is reported here for as long as the attempt to
	// obtain that capacity is still in progress. It moves to `blockedNodes` under the
	// `ReplacementUnavailable` reason only once the attempt has been given up on, because no
	// configuration allowed by this ComputeClass could supply the replacement. In short,
	// `migratingNodes` means the capacity is still expected to arrive, whereas
	// `ReplacementUnavailable` means it was asked for and could not be obtained.
	MigratingNodes *int `json:"migratingNodes,omitempty"`
	// BlockedNodes represents the number of nodes running on an outdated configuration whose
	// migration cannot proceed, grouped by the reason that blocks them. Each node is reported
	// under at most one reason. Reasons with no blocked nodes are not reported.
	BlockedNodes []BlockedNodesInfoApplyConfiguration `json:"blockedNodes,omitempty"`
	// MeasuredAt represents the timestamp at which the reported information was measured.
	MeasuredAt *metav1.Time `json:"measuredAt,omitempty"`
}

// ConfigDriftStatusApplyConfiguration constructs a declarative configuration of the ConfigDriftStatus type for use with
// apply.
func ConfigDriftStatus() *ConfigDriftStatusApplyConfiguration {
	return &ConfigDriftStatusApplyConfiguration{}
}

// WithCurrentNodes sets the CurrentNodes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentNodes field is set to the value of the last call.
func (b *ConfigDriftStatusApplyConfiguration) WithCurrentNodes(value int) *ConfigDriftStatusApplyConfiguration {
	b.CurrentNodes = &value
	return b
}

// WithDriftedNodes sets the DriftedNodes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DriftedNodes field is set to the value of the last call.
func (b *ConfigDriftStatusApplyConfiguration) WithDriftedNodes(value int) *ConfigDriftStatusApplyConfiguration {
	b.DriftedNodes = &value
	return b
}

// WithMigratingNodes sets the MigratingNodes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MigratingNodes field is set to the value of the last call.
func (b *ConfigDriftStatusApplyConfiguration) WithMigratingNodes(value int) *ConfigDriftStatusApplyConfiguration {
	b.MigratingNodes = &value
	return b
}

// WithBlockedNodes adds the given value to the BlockedNodes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the BlockedNodes field.
func (b *ConfigDriftStatusApplyConfiguration) WithBlockedNodes(values ...*BlockedNodesInfoApplyConfiguration) *ConfigDriftStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithBlockedNodes")
		}
		b.BlockedNodes = append(b.BlockedNodes, *values[i])
	}
	return b
}

// WithMeasuredAt sets the MeasuredAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MeasuredAt field is set to the value of the last call.
func (b *ConfigDriftStatusApplyConfiguration) WithMeasuredAt(value metav1.Time) *ConfigDriftStatusApplyConfiguration {
	b.MeasuredAt = &value
	return b
}
