/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ConsolidationBlockedNodesInfoApplyConfiguration represents a declarative configuration of the ConsolidationBlockedNodesInfo type for use
// with apply.
//
// ConsolidationBlockedNodesInfo describes how many nodes are blocked from being consolidated by a
// single reason.
type ConsolidationBlockedNodesInfoApplyConfiguration struct {
	// Reason identifies why the reported nodes cannot be consolidated.
	// Possible values:
	// * NodeNotReady - the node is not ready, and consolidation of unready nodes is disabled or the
	// node has not been unready for long enough.
	// * NodeConsolidationDisabled - the node opted out of removal, for example with the
	// "cluster-autoscaler.kubernetes.io/scale-down-disabled" annotation.
	// * AboveUtilizationThreshold - the node is too well utilized to be considered unneeded.
	// * NotUnneededLongEnough - the node is unneeded but has not been unneeded for long enough to
	// be removed yet.
	// * MinCapacityReached - removing the node would take the priority below a configured minimum,
	// such as the minimum capacity required by the compute class or the node pool minimum size.
	// * BlockingPods - a pod running on the node prevents it from being drained, for example a pod
	// that is not backed by a controller, one that uses local storage, or one that opted out of
	// eviction with the "cluster-autoscaler.kubernetes.io/safe-to-evict" annotation.
	// * PodDisruptionBudget - draining the node would violate a PodDisruptionBudget.
	// * NoPlaceToMovePods - the pods running on the node are evictable, but there is nowhere else
	// in the cluster to reschedule them.
	// * UsedByFormedSlice - the node belongs to a multi-host accelerator slice that is currently
	// formed, so it cannot be removed independently of that slice.
	// * AtomicGroupBlocked - the node belongs to an atomically scaled group in which another node
	// is blocked, so the whole group must be kept.
	// * RecentConsolidationFailure - a recent attempt to remove the node failed and it is backed off.
	// * ConsolidationBlocked - the node cannot be removed for a reason that is not reported more
	// specifically.
	Reason *string `json:"reason,omitempty"`
	// NodeCount represents the number of nodes blocked by this reason. It is always at least 1.
	NodeCount *int `json:"nodeCount,omitempty"`
	// TopologyUnitCount represents how many topology units contain at least one node blocked by
	// this reason. A topology unit is a set of nodes that the hardware topology forces to be
	// provisioned and removed together, such as a TPU cube or a multi-host accelerator slice. A
	// single blocked node keeps its whole unit, so 4 nodes blocked in one unit hold back 1 unit,
	// while 4 nodes blocked in 4 different units hold back all 4. A unit may contain nodes
	// blocked by different reasons, so the counts summed across reasons can exceed the number of
	// units in the priority. Only reported for priorities whose nodes form such units.
	TopologyUnitCount *int `json:"topologyUnitCount,omitempty"`
}

// ConsolidationBlockedNodesInfoApplyConfiguration constructs a declarative configuration of the ConsolidationBlockedNodesInfo type for use with
// apply.
func ConsolidationBlockedNodesInfo() *ConsolidationBlockedNodesInfoApplyConfiguration {
	return &ConsolidationBlockedNodesInfoApplyConfiguration{}
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *ConsolidationBlockedNodesInfoApplyConfiguration) WithReason(value string) *ConsolidationBlockedNodesInfoApplyConfiguration {
	b.Reason = &value
	return b
}

// WithNodeCount sets the NodeCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeCount field is set to the value of the last call.
func (b *ConsolidationBlockedNodesInfoApplyConfiguration) WithNodeCount(value int) *ConsolidationBlockedNodesInfoApplyConfiguration {
	b.NodeCount = &value
	return b
}

// WithTopologyUnitCount sets the TopologyUnitCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TopologyUnitCount field is set to the value of the last call.
func (b *ConsolidationBlockedNodesInfoApplyConfiguration) WithTopologyUnitCount(value int) *ConsolidationBlockedNodesInfoApplyConfiguration {
	b.TopologyUnitCount = &value
	return b
}
