/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ConsolidationStatusApplyConfiguration represents a declarative configuration of the ConsolidationStatus type for use
// with apply.
//
// ConsolidationStatus describes the progress of consolidating (scaling down) the nodes of a
// priority. It reports why spare capacity in the priority is not being reclaimed, without
// requiring the user to inspect individual nodes.
//
// Every node in the priority is accounted for in exactly one of `actuationInProgress`,
// `notProcessed` or `blockedNodes`, so the three together sum to the number of nodes in the
// priority. A node that is simply in use is reported under `blockedNodes` with reason
// `AboveUtilizationThreshold`; a node the autoscaler reached no verdict on in the last pass is
// reported under `notProcessed`.
type ConsolidationStatusApplyConfiguration struct {
	// ActuationInProgress represents the number of nodes that are currently being removed. This
	// includes nodes that are cordoned, being drained, or being deleted.
	ActuationInProgress *int `json:"actuationInProgress,omitempty"`
	// NotProcessed represents the number of nodes the autoscaler reached no verdict on in the
	// last pass, for example because a limit on how many nodes may be considered at once was
	// reached, or because the node was never evaluated as a removal candidate. These nodes are
	// neither known to be removable nor known to be blocked; they are expected to be evaluated
	// in a subsequent pass.
	NotProcessed *int `json:"notProcessed,omitempty"`
	// BlockedNodes represents the number of nodes that could be removed but cannot, grouped by the
	// reason that blocks them. Each node is reported under at most one reason. Reasons with no
	// blocked nodes are not reported.
	BlockedNodes []ConsolidationBlockedNodesInfoApplyConfiguration `json:"blockedNodes,omitempty"`
	// MeasuredAt represents the timestamp at which the reported information was measured.
	MeasuredAt *metav1.Time `json:"measuredAt,omitempty"`
}

// ConsolidationStatusApplyConfiguration constructs a declarative configuration of the ConsolidationStatus type for use with
// apply.
func ConsolidationStatus() *ConsolidationStatusApplyConfiguration {
	return &ConsolidationStatusApplyConfiguration{}
}

// WithActuationInProgress sets the ActuationInProgress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActuationInProgress field is set to the value of the last call.
func (b *ConsolidationStatusApplyConfiguration) WithActuationInProgress(value int) *ConsolidationStatusApplyConfiguration {
	b.ActuationInProgress = &value
	return b
}

// WithNotProcessed sets the NotProcessed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NotProcessed field is set to the value of the last call.
func (b *ConsolidationStatusApplyConfiguration) WithNotProcessed(value int) *ConsolidationStatusApplyConfiguration {
	b.NotProcessed = &value
	return b
}

// WithBlockedNodes adds the given value to the BlockedNodes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the BlockedNodes field.
func (b *ConsolidationStatusApplyConfiguration) WithBlockedNodes(values ...*ConsolidationBlockedNodesInfoApplyConfiguration) *ConsolidationStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithBlockedNodes")
		}
		b.BlockedNodes = append(b.BlockedNodes, *values[i])
	}
	return b
}

// WithMeasuredAt sets the MeasuredAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MeasuredAt field is set to the value of the last call.
func (b *ConsolidationStatusApplyConfiguration) WithMeasuredAt(value metav1.Time) *ConsolidationStatusApplyConfiguration {
	b.MeasuredAt = &value
	return b
}
