/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	cloudgooglecomv1 "github.com/googlecloudplatform/compute-class-api/api/cloud.google.com/v1"
)

// ContainerdConfigApplyConfiguration represents a declarative configuration of the ContainerdConfig type for use
// with apply.
//
// ContainerdConfig defines customization for containerd.
type ContainerdConfigApplyConfiguration struct {
	// PrivateRegistryAccessConfig defines access configuration for private container registries.
	PrivateRegistryAccessConfig *PrivateRegistryAccessConfigApplyConfiguration `json:"privateRegistryAccessConfig,omitempty"`
	// WritableCgroups defines writable cgroups configuration for the node pool.
	WritableCgroups *WritableCgroupsApplyConfiguration `json:"writableCgroups,omitempty"`
	// RegistryHosts defines containerd registry host configuration.
	RegistryHosts []*cloudgooglecomv1.RegistryHostConfig `json:"registryHosts,omitempty"`
}

// ContainerdConfigApplyConfiguration constructs a declarative configuration of the ContainerdConfig type for use with
// apply.
func ContainerdConfig() *ContainerdConfigApplyConfiguration {
	return &ContainerdConfigApplyConfiguration{}
}

// WithPrivateRegistryAccessConfig sets the PrivateRegistryAccessConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrivateRegistryAccessConfig field is set to the value of the last call.
func (b *ContainerdConfigApplyConfiguration) WithPrivateRegistryAccessConfig(value *PrivateRegistryAccessConfigApplyConfiguration) *ContainerdConfigApplyConfiguration {
	b.PrivateRegistryAccessConfig = value
	return b
}

// WithWritableCgroups sets the WritableCgroups field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WritableCgroups field is set to the value of the last call.
func (b *ContainerdConfigApplyConfiguration) WithWritableCgroups(value *WritableCgroupsApplyConfiguration) *ContainerdConfigApplyConfiguration {
	b.WritableCgroups = value
	return b
}

// WithRegistryHosts adds the given value to the RegistryHosts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RegistryHosts field.
func (b *ContainerdConfigApplyConfiguration) WithRegistryHosts(values ...**cloudgooglecomv1.RegistryHostConfig) *ContainerdConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRegistryHosts")
		}
		b.RegistryHosts = append(b.RegistryHosts, *values[i])
	}
	return b
}
