/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// DisruptionBudgetApplyConfiguration represents a declarative configuration of the DisruptionBudget type for use
// with apply.
//
// DisruptionBudget limits the number of nodes that can be concurrently migrated.
type DisruptionBudgetApplyConfiguration struct {
	// MaxNodes defines the maximum number of nodes that can be concurrently migrated.
	MaxNodes *int32 `json:"maxNodes,omitempty"`
}

// DisruptionBudgetApplyConfiguration constructs a declarative configuration of the DisruptionBudget type for use with
// apply.
func DisruptionBudget() *DisruptionBudgetApplyConfiguration {
	return &DisruptionBudgetApplyConfiguration{}
}

// WithMaxNodes sets the MaxNodes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxNodes field is set to the value of the last call.
func (b *DisruptionBudgetApplyConfiguration) WithMaxNodes(value int32) *DisruptionBudgetApplyConfiguration {
	b.MaxNodes = &value
	return b
}
