/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// EphemeralStorageLocalSsdConfigApplyConfiguration represents a declarative configuration of the EphemeralStorageLocalSsdConfig type for use
// with apply.
//
// EphemeralStorageLocalSsdConfig configures Local SSDs for ephemeral storage and mixed mode partitioning.
type EphemeralStorageLocalSsdConfigApplyConfiguration struct {
	// LocalSSDCount specifies the number of physical local SSDs attached to the node.
	// Optional for machine series with a fixed number of local SSDs (e.g., A3, A4X, Z4),
	// where it defaults to the fixed number of SSDs for that machine type.
	// Required for machine series with configurable local SSD counts (e.g., N2, C4).
	LocalSSDCount *int `json:"localSSDCount,omitempty"`
	// EphemeralCapacityGb specifies the capacity in GB carved out for the
	// ephemeral storage filesystem. The remaining Local SSD capacity is exposed
	// as unformatted raw block partitions (/dev/disk/by-id/google-local-ssd-partition*).
	// If omitted when ephemeralStorageLocalSsdConfig is set, 100% of attached Local SSD capacity is used for ephemeral storage.
	EphemeralCapacityGb *int64 `json:"ephemeralCapacityGb,omitempty"`
	// Enabled enables ephemeral storage local SSD mode.
	// Optional when localSSDCount or ephemeralCapacityGb is specified; required when both are omitted.
	// Must be true if set.
	Enabled *bool `json:"enabled,omitempty"`
}

// EphemeralStorageLocalSsdConfigApplyConfiguration constructs a declarative configuration of the EphemeralStorageLocalSsdConfig type for use with
// apply.
func EphemeralStorageLocalSsdConfig() *EphemeralStorageLocalSsdConfigApplyConfiguration {
	return &EphemeralStorageLocalSsdConfigApplyConfiguration{}
}

// WithLocalSSDCount sets the LocalSSDCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocalSSDCount field is set to the value of the last call.
func (b *EphemeralStorageLocalSsdConfigApplyConfiguration) WithLocalSSDCount(value int) *EphemeralStorageLocalSsdConfigApplyConfiguration {
	b.LocalSSDCount = &value
	return b
}

// WithEphemeralCapacityGb sets the EphemeralCapacityGb field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EphemeralCapacityGb field is set to the value of the last call.
func (b *EphemeralStorageLocalSsdConfigApplyConfiguration) WithEphemeralCapacityGb(value int64) *EphemeralStorageLocalSsdConfigApplyConfiguration {
	b.EphemeralCapacityGb = &value
	return b
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *EphemeralStorageLocalSsdConfigApplyConfiguration) WithEnabled(value bool) *EphemeralStorageLocalSsdConfigApplyConfiguration {
	b.Enabled = &value
	return b
}
