/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// EvictionSoftApplyConfiguration represents a declarative configuration of the EvictionSoft type for use
// with apply.
type EvictionSoftApplyConfiguration struct {
	MemoryAvailable   *string `json:"memoryAvailable,omitempty"`
	NodefsAvailable   *string `json:"nodefsAvailable,omitempty"`
	ImagefsAvailable  *string `json:"imagefsAvailable,omitempty"`
	ImagefsInodesFree *string `json:"imagefsInodesFree,omitempty"`
	NodefsInodesFree  *string `json:"nodefsInodesFree,omitempty"`
	PidAvailable      *string `json:"pidAvailable,omitempty"`
}

// EvictionSoftApplyConfiguration constructs a declarative configuration of the EvictionSoft type for use with
// apply.
func EvictionSoft() *EvictionSoftApplyConfiguration {
	return &EvictionSoftApplyConfiguration{}
}

// WithMemoryAvailable sets the MemoryAvailable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MemoryAvailable field is set to the value of the last call.
func (b *EvictionSoftApplyConfiguration) WithMemoryAvailable(value string) *EvictionSoftApplyConfiguration {
	b.MemoryAvailable = &value
	return b
}

// WithNodefsAvailable sets the NodefsAvailable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodefsAvailable field is set to the value of the last call.
func (b *EvictionSoftApplyConfiguration) WithNodefsAvailable(value string) *EvictionSoftApplyConfiguration {
	b.NodefsAvailable = &value
	return b
}

// WithImagefsAvailable sets the ImagefsAvailable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImagefsAvailable field is set to the value of the last call.
func (b *EvictionSoftApplyConfiguration) WithImagefsAvailable(value string) *EvictionSoftApplyConfiguration {
	b.ImagefsAvailable = &value
	return b
}

// WithImagefsInodesFree sets the ImagefsInodesFree field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImagefsInodesFree field is set to the value of the last call.
func (b *EvictionSoftApplyConfiguration) WithImagefsInodesFree(value string) *EvictionSoftApplyConfiguration {
	b.ImagefsInodesFree = &value
	return b
}

// WithNodefsInodesFree sets the NodefsInodesFree field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodefsInodesFree field is set to the value of the last call.
func (b *EvictionSoftApplyConfiguration) WithNodefsInodesFree(value string) *EvictionSoftApplyConfiguration {
	b.NodefsInodesFree = &value
	return b
}

// WithPidAvailable sets the PidAvailable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PidAvailable field is set to the value of the last call.
func (b *EvictionSoftApplyConfiguration) WithPidAvailable(value string) *EvictionSoftApplyConfiguration {
	b.PidAvailable = &value
	return b
}
