/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// GCPSecretManagerCertificateConfigApplyConfiguration represents a declarative configuration of the GCPSecretManagerCertificateConfig type for use
// with apply.
//
// GCPSecretManagerCertificateConfig specifies the location of CA certificates stored in Google Cloud Secret Manager.
type GCPSecretManagerCertificateConfigApplyConfiguration struct {
	// SecretURI specifies the location of the secret in Google Cloud Secret Manager.
	SecretURI *string `json:"secretURI,omitempty"`
}

// GCPSecretManagerCertificateConfigApplyConfiguration constructs a declarative configuration of the GCPSecretManagerCertificateConfig type for use with
// apply.
func GCPSecretManagerCertificateConfig() *GCPSecretManagerCertificateConfigApplyConfiguration {
	return &GCPSecretManagerCertificateConfigApplyConfiguration{}
}

// WithSecretURI sets the SecretURI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretURI field is set to the value of the last call.
func (b *GCPSecretManagerCertificateConfigApplyConfiguration) WithSecretURI(value string) *GCPSecretManagerCertificateConfigApplyConfiguration {
	b.SecretURI = &value
	return b
}
