/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	cloudgooglecomv1 "github.com/googlecloudplatform/compute-class-api/api/cloud.google.com/v1"
)

// GoogleTpuApplyConfiguration represents a declarative configuration of the GoogleTpu type for use
// with apply.
type GoogleTpuApplyConfiguration struct {
	DriverMode *cloudgooglecomv1.TpuDriverMode `json:"driverMode,omitempty"`
}

// GoogleTpuApplyConfiguration constructs a declarative configuration of the GoogleTpu type for use with
// apply.
func GoogleTpu() *GoogleTpuApplyConfiguration {
	return &GoogleTpuApplyConfiguration{}
}

// WithDriverMode sets the DriverMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DriverMode field is set to the value of the last call.
func (b *GoogleTpuApplyConfiguration) WithDriverMode(value cloudgooglecomv1.TpuDriverMode) *GoogleTpuApplyConfiguration {
	b.DriverMode = &value
	return b
}
