/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// GoogleTpuDraDriverApplyConfiguration represents an declarative configuration of the GoogleTpuDraDriver type for use
// with apply.
type GoogleTpuDraDriverApplyConfiguration struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// GoogleTpuDraDriverApplyConfiguration constructs an declarative configuration of the GoogleTpuDraDriver type for use with
// apply.
func GoogleTpuDraDriver() *GoogleTpuDraDriverApplyConfiguration {
	return &GoogleTpuDraDriverApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *GoogleTpuDraDriverApplyConfiguration) WithEnabled(value bool) *GoogleTpuDraDriverApplyConfiguration {
	b.Enabled = &value
	return b
}
