/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// GPUApplyConfiguration represents an declarative configuration of the GPU type for use
// with apply.
type GPUApplyConfiguration struct {
	Type          *string                       `json:"type,omitempty"`
	Count         *int64                        `json:"count,omitempty"`
	DriverVersion *string                       `json:"driverVersion,omitempty"`
	Topology      *string                       `json:"topology,omitempty"`
	GpuSharing    *GpuSharingApplyConfiguration `json:"gpuSharing,omitempty"`
}

// GPUApplyConfiguration constructs an declarative configuration of the GPU type for use with
// apply.
func GPU() *GPUApplyConfiguration {
	return &GPUApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *GPUApplyConfiguration) WithType(value string) *GPUApplyConfiguration {
	b.Type = &value
	return b
}

// WithCount sets the Count field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Count field is set to the value of the last call.
func (b *GPUApplyConfiguration) WithCount(value int64) *GPUApplyConfiguration {
	b.Count = &value
	return b
}

// WithDriverVersion sets the DriverVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DriverVersion field is set to the value of the last call.
func (b *GPUApplyConfiguration) WithDriverVersion(value string) *GPUApplyConfiguration {
	b.DriverVersion = &value
	return b
}

// WithTopology sets the Topology field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Topology field is set to the value of the last call.
func (b *GPUApplyConfiguration) WithTopology(value string) *GPUApplyConfiguration {
	b.Topology = &value
	return b
}

// WithGpuSharing sets the GpuSharing field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GpuSharing field is set to the value of the last call.
func (b *GPUApplyConfiguration) WithGpuSharing(value *GpuSharingApplyConfiguration) *GPUApplyConfiguration {
	b.GpuSharing = value
	return b
}
