/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// GpuSharingApplyConfiguration represents an declarative configuration of the GpuSharing type for use
// with apply.
type GpuSharingApplyConfiguration struct {
	SharingStrategy        *string `json:"sharingStrategy,omitempty"`
	MaxSharedClientsPerGPU *int64  `json:"maxSharedClientsPerGPU,omitempty"`
	GpuPartitionSize       *string `json:"gpuPartitionSize,omitempty"`
}

// GpuSharingApplyConfiguration constructs an declarative configuration of the GpuSharing type for use with
// apply.
func GpuSharing() *GpuSharingApplyConfiguration {
	return &GpuSharingApplyConfiguration{}
}

// WithSharingStrategy sets the SharingStrategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SharingStrategy field is set to the value of the last call.
func (b *GpuSharingApplyConfiguration) WithSharingStrategy(value string) *GpuSharingApplyConfiguration {
	b.SharingStrategy = &value
	return b
}

// WithMaxSharedClientsPerGPU sets the MaxSharedClientsPerGPU field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxSharedClientsPerGPU field is set to the value of the last call.
func (b *GpuSharingApplyConfiguration) WithMaxSharedClientsPerGPU(value int64) *GpuSharingApplyConfiguration {
	b.MaxSharedClientsPerGPU = &value
	return b
}

// WithGpuPartitionSize sets the GpuPartitionSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GpuPartitionSize field is set to the value of the last call.
func (b *GpuSharingApplyConfiguration) WithGpuPartitionSize(value string) *GpuSharingApplyConfiguration {
	b.GpuPartitionSize = &value
	return b
}
