/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// HugepagesConfigApplyConfiguration represents an declarative configuration of the HugepagesConfig type for use
// with apply.
type HugepagesConfigApplyConfiguration struct {
	HugepageSize1g *int64 `json:"hugepage_size1g,omitempty"`
	HugepageSize2m *int64 `json:"hugepage_size2m,omitempty"`
}

// HugepagesConfigApplyConfiguration constructs an declarative configuration of the HugepagesConfig type for use with
// apply.
func HugepagesConfig() *HugepagesConfigApplyConfiguration {
	return &HugepagesConfigApplyConfiguration{}
}

// WithHugepageSize1g sets the HugepageSize1g field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HugepageSize1g field is set to the value of the last call.
func (b *HugepagesConfigApplyConfiguration) WithHugepageSize1g(value int64) *HugepagesConfigApplyConfiguration {
	b.HugepageSize1g = &value
	return b
}

// WithHugepageSize2m sets the HugepageSize2m field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HugepageSize2m field is set to the value of the last call.
func (b *HugepagesConfigApplyConfiguration) WithHugepageSize2m(value int64) *HugepagesConfigApplyConfiguration {
	b.HugepageSize2m = &value
	return b
}
