/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// KernelOverridesApplyConfiguration represents an declarative configuration of the KernelOverrides type for use
// with apply.
type KernelOverridesApplyConfiguration struct {
	KernelCommandlineOverrides *KernelCommandlineOverridesApplyConfiguration `json:"kernelCommandlineOverrides,omitempty"`
	LruGen                     *LRUGenApplyConfiguration                     `json:"lruGen,omitempty"`
}

// KernelOverridesApplyConfiguration constructs an declarative configuration of the KernelOverrides type for use with
// apply.
func KernelOverrides() *KernelOverridesApplyConfiguration {
	return &KernelOverridesApplyConfiguration{}
}

// WithKernelCommandlineOverrides sets the KernelCommandlineOverrides field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KernelCommandlineOverrides field is set to the value of the last call.
func (b *KernelOverridesApplyConfiguration) WithKernelCommandlineOverrides(value *KernelCommandlineOverridesApplyConfiguration) *KernelOverridesApplyConfiguration {
	b.KernelCommandlineOverrides = value
	return b
}

// WithLruGen sets the LruGen field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LruGen field is set to the value of the last call.
func (b *KernelOverridesApplyConfiguration) WithLruGen(value *LRUGenApplyConfiguration) *KernelOverridesApplyConfiguration {
	b.LruGen = value
	return b
}
