/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// KubeletConfigApplyConfiguration represents an declarative configuration of the KubeletConfig type for use
// with apply.
type KubeletConfigApplyConfiguration struct {
	CpuCfsQuota                      *bool                                      `json:"cpuCfsQuota,omitempty"`
	CpuCfsQuotaPeriod                *string                                    `json:"cpuCfsQuotaPeriod,omitempty"`
	CpuManagerPolicy                 *string                                    `json:"cpuManagerPolicy,omitempty"`
	PodPidsLimit                     *int64                                     `json:"podPidsLimit,omitempty"`
	ImageGcLowThresholdPercent       *int64                                     `json:"imageGcLowThresholdPercent,omitempty"`
	ImageGcHighThresholdPercent      *int64                                     `json:"imageGcHighThresholdPercent,omitempty"`
	ImageMinimumGcAge                *string                                    `json:"imageMinimumGcAge,omitempty"`
	ImageMaximumGcAge                *string                                    `json:"imageMaximumGcAge,omitempty"`
	ContainerLogMaxSize              *string                                    `json:"containerLogMaxSize,omitempty"`
	ContainerLogMaxFiles             *int64                                     `json:"containerLogMaxFiles,omitempty"`
	AllowedUnsafeSysctls             []string                                   `json:"allowedUnsafeSysctls,omitempty"`
	MaxParallelImagePulls            *int64                                     `json:"maxParallelImagePulls,omitempty"`
	SingleProcessOOMKill             *bool                                      `json:"singleProcessOOMKill,omitempty"`
	EvictionSoft                     *EvictionSoftApplyConfiguration            `json:"evictionSoft,omitempty"`
	EvictionSoftGracePeriod          *EvictionSoftGracePeriodApplyConfiguration `json:"evictionSoftGracePeriod,omitempty"`
	EvictionMinimumReclaim           *EvictionMinimumReclaimApplyConfiguration  `json:"evictionMinimumReclaim,omitempty"`
	EvictionMaxPodGracePeriodSeconds *int64                                     `json:"evictionMaxPodGracePeriodSeconds,omitempty"`
	TopologyManager                  *TopologyManagerApplyConfiguration         `json:"topologyManager,omitempty"`
	MemoryManager                    *MemoryManagerApplyConfiguration           `json:"memoryManager,omitempty"`
}

// KubeletConfigApplyConfiguration constructs an declarative configuration of the KubeletConfig type for use with
// apply.
func KubeletConfig() *KubeletConfigApplyConfiguration {
	return &KubeletConfigApplyConfiguration{}
}

// WithCpuCfsQuota sets the CpuCfsQuota field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CpuCfsQuota field is set to the value of the last call.
func (b *KubeletConfigApplyConfiguration) WithCpuCfsQuota(value bool) *KubeletConfigApplyConfiguration {
	b.CpuCfsQuota = &value
	return b
}

// WithCpuCfsQuotaPeriod sets the CpuCfsQuotaPeriod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CpuCfsQuotaPeriod field is set to the value of the last call.
func (b *KubeletConfigApplyConfiguration) WithCpuCfsQuotaPeriod(value string) *KubeletConfigApplyConfiguration {
	b.CpuCfsQuotaPeriod = &value
	return b
}

// WithCpuManagerPolicy sets the CpuManagerPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CpuManagerPolicy field is set to the value of the last call.
func (b *KubeletConfigApplyConfiguration) WithCpuManagerPolicy(value string) *KubeletConfigApplyConfiguration {
	b.CpuManagerPolicy = &value
	return b
}

// WithPodPidsLimit sets the PodPidsLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodPidsLimit field is set to the value of the last call.
func (b *KubeletConfigApplyConfiguration) WithPodPidsLimit(value int64) *KubeletConfigApplyConfiguration {
	b.PodPidsLimit = &value
	return b
}

// WithImageGcLowThresholdPercent sets the ImageGcLowThresholdPercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageGcLowThresholdPercent field is set to the value of the last call.
func (b *KubeletConfigApplyConfiguration) WithImageGcLowThresholdPercent(value int64) *KubeletConfigApplyConfiguration {
	b.ImageGcLowThresholdPercent = &value
	return b
}

// WithImageGcHighThresholdPercent sets the ImageGcHighThresholdPercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageGcHighThresholdPercent field is set to the value of the last call.
func (b *KubeletConfigApplyConfiguration) WithImageGcHighThresholdPercent(value int64) *KubeletConfigApplyConfiguration {
	b.ImageGcHighThresholdPercent = &value
	return b
}

// WithImageMinimumGcAge sets the ImageMinimumGcAge field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageMinimumGcAge field is set to the value of the last call.
func (b *KubeletConfigApplyConfiguration) WithImageMinimumGcAge(value string) *KubeletConfigApplyConfiguration {
	b.ImageMinimumGcAge = &value
	return b
}

// WithImageMaximumGcAge sets the ImageMaximumGcAge field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageMaximumGcAge field is set to the value of the last call.
func (b *KubeletConfigApplyConfiguration) WithImageMaximumGcAge(value string) *KubeletConfigApplyConfiguration {
	b.ImageMaximumGcAge = &value
	return b
}

// WithContainerLogMaxSize sets the ContainerLogMaxSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContainerLogMaxSize field is set to the value of the last call.
func (b *KubeletConfigApplyConfiguration) WithContainerLogMaxSize(value string) *KubeletConfigApplyConfiguration {
	b.ContainerLogMaxSize = &value
	return b
}

// WithContainerLogMaxFiles sets the ContainerLogMaxFiles field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContainerLogMaxFiles field is set to the value of the last call.
func (b *KubeletConfigApplyConfiguration) WithContainerLogMaxFiles(value int64) *KubeletConfigApplyConfiguration {
	b.ContainerLogMaxFiles = &value
	return b
}

// WithAllowedUnsafeSysctls adds the given value to the AllowedUnsafeSysctls field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedUnsafeSysctls field.
func (b *KubeletConfigApplyConfiguration) WithAllowedUnsafeSysctls(values ...string) *KubeletConfigApplyConfiguration {
	for i := range values {
		b.AllowedUnsafeSysctls = append(b.AllowedUnsafeSysctls, values[i])
	}
	return b
}

// WithMaxParallelImagePulls sets the MaxParallelImagePulls field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxParallelImagePulls field is set to the value of the last call.
func (b *KubeletConfigApplyConfiguration) WithMaxParallelImagePulls(value int64) *KubeletConfigApplyConfiguration {
	b.MaxParallelImagePulls = &value
	return b
}

// WithSingleProcessOOMKill sets the SingleProcessOOMKill field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SingleProcessOOMKill field is set to the value of the last call.
func (b *KubeletConfigApplyConfiguration) WithSingleProcessOOMKill(value bool) *KubeletConfigApplyConfiguration {
	b.SingleProcessOOMKill = &value
	return b
}

// WithEvictionSoft sets the EvictionSoft field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EvictionSoft field is set to the value of the last call.
func (b *KubeletConfigApplyConfiguration) WithEvictionSoft(value *EvictionSoftApplyConfiguration) *KubeletConfigApplyConfiguration {
	b.EvictionSoft = value
	return b
}

// WithEvictionSoftGracePeriod sets the EvictionSoftGracePeriod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EvictionSoftGracePeriod field is set to the value of the last call.
func (b *KubeletConfigApplyConfiguration) WithEvictionSoftGracePeriod(value *EvictionSoftGracePeriodApplyConfiguration) *KubeletConfigApplyConfiguration {
	b.EvictionSoftGracePeriod = value
	return b
}

// WithEvictionMinimumReclaim sets the EvictionMinimumReclaim field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EvictionMinimumReclaim field is set to the value of the last call.
func (b *KubeletConfigApplyConfiguration) WithEvictionMinimumReclaim(value *EvictionMinimumReclaimApplyConfiguration) *KubeletConfigApplyConfiguration {
	b.EvictionMinimumReclaim = value
	return b
}

// WithEvictionMaxPodGracePeriodSeconds sets the EvictionMaxPodGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EvictionMaxPodGracePeriodSeconds field is set to the value of the last call.
func (b *KubeletConfigApplyConfiguration) WithEvictionMaxPodGracePeriodSeconds(value int64) *KubeletConfigApplyConfiguration {
	b.EvictionMaxPodGracePeriodSeconds = &value
	return b
}

// WithTopologyManager sets the TopologyManager field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TopologyManager field is set to the value of the last call.
func (b *KubeletConfigApplyConfiguration) WithTopologyManager(value *TopologyManagerApplyConfiguration) *KubeletConfigApplyConfiguration {
	b.TopologyManager = value
	return b
}

// WithMemoryManager sets the MemoryManager field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MemoryManager field is set to the value of the last call.
func (b *KubeletConfigApplyConfiguration) WithMemoryManager(value *MemoryManagerApplyConfiguration) *KubeletConfigApplyConfiguration {
	b.MemoryManager = value
	return b
}
