/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	cloudgooglecomv1 "github.com/googlecloudplatform/compute-class-api/api/cloud.google.com/v1"
)

// LinuxNodeConfigApplyConfiguration represents a declarative configuration of the LinuxNodeConfig type for use
// with apply.
//
// LinuxNodeConfig defines linux node config for a node.
type LinuxNodeConfigApplyConfiguration struct {
	Sysctls   *SysctlsConfigApplyConfiguration   `json:"sysctls,omitempty"`
	Hugepages *HugepagesConfigApplyConfiguration `json:"hugepageConfig,omitempty"`
	// Controls transparent hugepage support for anonymous memory. Currently supported values:
	// * TRANSPARENT_HUGEPAGE_ENABLED_ALWAYS: Transparent hugepage is enabled system wide.
	// * TRANSPARENT_HUGEPAGE_ENABLED_MADVISE: Transparent hugepage is enabled inside MADV_HUGEPAGE regions. This is the default kernel configuration.
	// * TRANSPARENT_HUGEPAGE_ENABLED_NEVER: Transparent hugepage is disabled.
	// * TRANSPARENT_HUGEPAGE_ENABLED_UNSPECIFIED: Default value. GKE will not modify the kernel configuration.
	TransparentHugepageEnabled *string `json:"transparentHugepageEnabled,omitempty"`
	// Defines the transparent hugepage defrag configuration on the node. Currently supported values:
	// * TRANSPARENT_HUGEPAGE_DEFRAG_ALWAYS: An application requesting THP will stall on allocation failure and directly reclaim pages and compact memory in an effort to allocate a THP immediately.
	// * TRANSPARENT_HUGEPAGE_DEFRAG_DEFER: An application will wake kswapd in the background to reclaim pages and wake kcompactd to compact memory so that THP is available in the near future. It is the responsibility of khugepaged to then install the THP pages later.
	// * TRANSPARENT_HUGEPAGE_DEFRAG_DEFER_WITH_MADVISE: An application will enter direct reclaim and compaction like always, but only for regions that have used madvise(MADV_HUGEPAGE); all other regions will wake kswapd in the background to reclaim pages and wake kcompactd to compact memory so that THP is available in the near future.
	// * TRANSPARENT_HUGEPAGE_DEFRAG_MADVISE: An application will enter direct reclaim and compaction like always, but only for regions that have used madvise(MADV_HUGEPAGE); all other regions will wake kswapd in the background to reclaim pages and wake kcompactd to compact memory so that THP is available in the near future.
	// * TRANSPARENT_HUGEPAGE_DEFRAG_NEVER: An application will never enter direct reclaim or compaction.
	// * TRANSPARENT_HUGEPAGE_DEFRAG_UNSPECIFIED: Default value. GKE will not modify the kernel configuration.
	TransparentHugepageDefrag *string                       `json:"transparentHugepageDefrag,omitempty"`
	SwapConfig                *SwapConfigApplyConfiguration `json:"swapConfig,omitempty"`
	// Additional entries to be added to /etc/hosts.
	AdditionalEtcHosts []*cloudgooglecomv1.EtcHostsEntry `json:"additionalEtcHosts,omitempty"`
	// Additional entries to be added to /etc/resolv.conf.
	AdditionalEtcResolvConf []*cloudgooglecomv1.ResolvedConfEntry `json:"additionalEtcResolvConf,omitempty"`
	// Additional entries to be added to /etc/systemd/resolved.conf.
	AdditionalEtcSystemdResolvedConf []*cloudgooglecomv1.ResolvedConfEntry `json:"additionalEtcSystemdResolvedConf,omitempty"`
	// Support for running custom init code while bootstrapping nodes.
	CustomNodeInit *CustomNodeInitApplyConfiguration `json:"customNodeInit,omitempty"`
	// Parameters that can be configured on the kernel.
	KernelOverrides *KernelOverridesApplyConfiguration `json:"kernelOverrides,omitempty"`
	// Configures the timezone of the node.
	TimeZone *string `json:"timeZone,omitempty"`
	// AccurateTimeConfig defines accurate time configuration for a node.
	AccurateTimeConfig *AccurateTimeConfigApplyConfiguration `json:"accurateTimeConfig,omitempty"`
	// Contains VFIO-related configurations for this node.
	NodeVfioConfig *NodeVfioConfigApplyConfiguration `json:"nodeVfioConfig,omitempty"`
	// Controls the configuration for the disk IO scheduler.
	DiskIoScheduler *DiskIoSchedulerApplyConfiguration `json:"diskIoScheduler,omitempty"`
}

// LinuxNodeConfigApplyConfiguration constructs a declarative configuration of the LinuxNodeConfig type for use with
// apply.
func LinuxNodeConfig() *LinuxNodeConfigApplyConfiguration {
	return &LinuxNodeConfigApplyConfiguration{}
}

// WithSysctls sets the Sysctls field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Sysctls field is set to the value of the last call.
func (b *LinuxNodeConfigApplyConfiguration) WithSysctls(value *SysctlsConfigApplyConfiguration) *LinuxNodeConfigApplyConfiguration {
	b.Sysctls = value
	return b
}

// WithHugepages sets the Hugepages field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hugepages field is set to the value of the last call.
func (b *LinuxNodeConfigApplyConfiguration) WithHugepages(value *HugepagesConfigApplyConfiguration) *LinuxNodeConfigApplyConfiguration {
	b.Hugepages = value
	return b
}

// WithTransparentHugepageEnabled sets the TransparentHugepageEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TransparentHugepageEnabled field is set to the value of the last call.
func (b *LinuxNodeConfigApplyConfiguration) WithTransparentHugepageEnabled(value string) *LinuxNodeConfigApplyConfiguration {
	b.TransparentHugepageEnabled = &value
	return b
}

// WithTransparentHugepageDefrag sets the TransparentHugepageDefrag field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TransparentHugepageDefrag field is set to the value of the last call.
func (b *LinuxNodeConfigApplyConfiguration) WithTransparentHugepageDefrag(value string) *LinuxNodeConfigApplyConfiguration {
	b.TransparentHugepageDefrag = &value
	return b
}

// WithSwapConfig sets the SwapConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SwapConfig field is set to the value of the last call.
func (b *LinuxNodeConfigApplyConfiguration) WithSwapConfig(value *SwapConfigApplyConfiguration) *LinuxNodeConfigApplyConfiguration {
	b.SwapConfig = value
	return b
}

// WithAdditionalEtcHosts adds the given value to the AdditionalEtcHosts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AdditionalEtcHosts field.
func (b *LinuxNodeConfigApplyConfiguration) WithAdditionalEtcHosts(values ...**cloudgooglecomv1.EtcHostsEntry) *LinuxNodeConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAdditionalEtcHosts")
		}
		b.AdditionalEtcHosts = append(b.AdditionalEtcHosts, *values[i])
	}
	return b
}

// WithAdditionalEtcResolvConf adds the given value to the AdditionalEtcResolvConf field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AdditionalEtcResolvConf field.
func (b *LinuxNodeConfigApplyConfiguration) WithAdditionalEtcResolvConf(values ...**cloudgooglecomv1.ResolvedConfEntry) *LinuxNodeConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAdditionalEtcResolvConf")
		}
		b.AdditionalEtcResolvConf = append(b.AdditionalEtcResolvConf, *values[i])
	}
	return b
}

// WithAdditionalEtcSystemdResolvedConf adds the given value to the AdditionalEtcSystemdResolvedConf field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AdditionalEtcSystemdResolvedConf field.
func (b *LinuxNodeConfigApplyConfiguration) WithAdditionalEtcSystemdResolvedConf(values ...**cloudgooglecomv1.ResolvedConfEntry) *LinuxNodeConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAdditionalEtcSystemdResolvedConf")
		}
		b.AdditionalEtcSystemdResolvedConf = append(b.AdditionalEtcSystemdResolvedConf, *values[i])
	}
	return b
}

// WithCustomNodeInit sets the CustomNodeInit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomNodeInit field is set to the value of the last call.
func (b *LinuxNodeConfigApplyConfiguration) WithCustomNodeInit(value *CustomNodeInitApplyConfiguration) *LinuxNodeConfigApplyConfiguration {
	b.CustomNodeInit = value
	return b
}

// WithKernelOverrides sets the KernelOverrides field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KernelOverrides field is set to the value of the last call.
func (b *LinuxNodeConfigApplyConfiguration) WithKernelOverrides(value *KernelOverridesApplyConfiguration) *LinuxNodeConfigApplyConfiguration {
	b.KernelOverrides = value
	return b
}

// WithTimeZone sets the TimeZone field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TimeZone field is set to the value of the last call.
func (b *LinuxNodeConfigApplyConfiguration) WithTimeZone(value string) *LinuxNodeConfigApplyConfiguration {
	b.TimeZone = &value
	return b
}

// WithAccurateTimeConfig sets the AccurateTimeConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccurateTimeConfig field is set to the value of the last call.
func (b *LinuxNodeConfigApplyConfiguration) WithAccurateTimeConfig(value *AccurateTimeConfigApplyConfiguration) *LinuxNodeConfigApplyConfiguration {
	b.AccurateTimeConfig = value
	return b
}

// WithNodeVfioConfig sets the NodeVfioConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeVfioConfig field is set to the value of the last call.
func (b *LinuxNodeConfigApplyConfiguration) WithNodeVfioConfig(value *NodeVfioConfigApplyConfiguration) *LinuxNodeConfigApplyConfiguration {
	b.NodeVfioConfig = value
	return b
}

// WithDiskIoScheduler sets the DiskIoScheduler field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiskIoScheduler field is set to the value of the last call.
func (b *LinuxNodeConfigApplyConfiguration) WithDiskIoScheduler(value *DiskIoSchedulerApplyConfiguration) *LinuxNodeConfigApplyConfiguration {
	b.DiskIoScheduler = value
	return b
}
