/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// LocalNvmeSsdBlockConfigApplyConfiguration represents a declarative configuration of the LocalNvmeSsdBlockConfig type for use
// with apply.
//
// LocalNvmeSsdBlockConfig configures Local NVMe SSDs for raw block device access.
type LocalNvmeSsdBlockConfigApplyConfiguration struct {
	// LocalSSDCount specifies the number of physical local SSDs attached to the node as raw block devices.
	// Optional for machine series with a fixed number of local SSDs (e.g., A3, A4X, Z4),
	// where it defaults to the fixed number of SSDs for that machine type.
	// Required for machine series with configurable local SSD counts (e.g., N2, C4).
	LocalSSDCount *int `json:"localSSDCount,omitempty"`
	// Enabled enables local NVMe SSD block mode.
	// Optional when localSSDCount is specified; required when localSSDCount is omitted.
	// Must be true if set.
	Enabled *bool `json:"enabled,omitempty"`
}

// LocalNvmeSsdBlockConfigApplyConfiguration constructs a declarative configuration of the LocalNvmeSsdBlockConfig type for use with
// apply.
func LocalNvmeSsdBlockConfig() *LocalNvmeSsdBlockConfigApplyConfiguration {
	return &LocalNvmeSsdBlockConfigApplyConfiguration{}
}

// WithLocalSSDCount sets the LocalSSDCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocalSSDCount field is set to the value of the last call.
func (b *LocalNvmeSsdBlockConfigApplyConfiguration) WithLocalSSDCount(value int) *LocalNvmeSsdBlockConfigApplyConfiguration {
	b.LocalSSDCount = &value
	return b
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *LocalNvmeSsdBlockConfigApplyConfiguration) WithEnabled(value bool) *LocalNvmeSsdBlockConfigApplyConfiguration {
	b.Enabled = &value
	return b
}
