/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// MinimumCapacityApplyConfiguration represents an declarative configuration of the MinimumCapacity type for use
// with apply.
type MinimumCapacityApplyConfiguration struct {
	TargetNodeCount *int `json:"targetNodeCount,omitempty"`
}

// MinimumCapacityApplyConfiguration constructs an declarative configuration of the MinimumCapacity type for use with
// apply.
func MinimumCapacity() *MinimumCapacityApplyConfiguration {
	return &MinimumCapacityApplyConfiguration{}
}

// WithTargetNodeCount sets the TargetNodeCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetNodeCount field is set to the value of the last call.
func (b *MinimumCapacityApplyConfiguration) WithTargetNodeCount(value int) *MinimumCapacityApplyConfiguration {
	b.TargetNodeCount = &value
	return b
}
