/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// NetworkConfigApplyConfiguration represents a declarative configuration of the NetworkConfig type for use
// with apply.
//
// NetworkConfig defines network-related settings for the ComputeClass.
type NetworkConfigApplyConfiguration struct {
	// SubnetPriorities is an ordered list of subnets to fall back through.
	// TODO(b/552484145): Increase the max items to 5 once the API is updated to support multiple subnets.
	SubnetPriorities []SubnetPriorityApplyConfiguration `json:"subnetPriorities,omitempty"`
	// DisablePodCidrOverprovisionConfig allows disabling the default overprovisioning allocation of Pod CIDR ranges.
	DisablePodCidrOverprovisionConfig *bool `json:"disablePodCidrOverprovisionConfig,omitempty"`
}

// NetworkConfigApplyConfiguration constructs a declarative configuration of the NetworkConfig type for use with
// apply.
func NetworkConfig() *NetworkConfigApplyConfiguration {
	return &NetworkConfigApplyConfiguration{}
}

// WithSubnetPriorities adds the given value to the SubnetPriorities field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SubnetPriorities field.
func (b *NetworkConfigApplyConfiguration) WithSubnetPriorities(values ...*SubnetPriorityApplyConfiguration) *NetworkConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSubnetPriorities")
		}
		b.SubnetPriorities = append(b.SubnetPriorities, *values[i])
	}
	return b
}

// WithDisablePodCidrOverprovisionConfig sets the DisablePodCidrOverprovisionConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisablePodCidrOverprovisionConfig field is set to the value of the last call.
func (b *NetworkConfigApplyConfiguration) WithDisablePodCidrOverprovisionConfig(value bool) *NetworkConfigApplyConfiguration {
	b.DisablePodCidrOverprovisionConfig = &value
	return b
}
