/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	cloudgooglecomv1 "github.com/googlecloudplatform/compute-class-api/api/cloud.google.com/v1"
)

// NodePoolConfigApplyConfiguration represents a declarative configuration of the NodePoolConfig type for use
// with apply.
//
// NodePoolConfig defines required node pool configuration. Existing node pools will be matched with the ComputeClass
// only if their configuration match this field. Auto-provisioned node pools will be created with this configuration.
type NodePoolConfigApplyConfiguration struct {
	// ServiceAccount used by the node pool.
	ServiceAccount *string `json:"serviceAccount,omitempty"`
	// Image type used by nodes in the node pool.
	ImageType *string `json:"imageType,omitempty"`
	// WorkloadType defines Collection or Goodput SLO for the workload. Currently
	// supported values:
	// * HIGH_AVAILABILITY - for Collection SLO
	// * HIGH_THROUGHPUT - for Goodput SLO
	// HIGH_AVAILABILITY is desired for running serving workloads which require
	// most of the infrastructure (slices) running all the time to achieve high
	// availability.
	// HIGH_THROUGHPUT is desired for running batch/training jobs
	// which require all underlying infrastructure (slices) running for most of
	// the time to make progress. HIGH_THROUGHPUT can be only set for a multi-host
	// scenario, that is, when NodePoolGroup is set.
	WorkloadType *string `json:"workloadType,omitempty"`
	// NodeLabels is used to add user defined Kubernetes labels to all nodes in the new node pool.
	// These labels are applied to the Kubernetes API node object and can be used in nodeSelectors for pod scheduling.
	// Note: Node labels are distinct from GKE labels.
	// More info: https://cloud.google.com/sdk/gcloud/reference/container/node-pools/create#--node-labels
	NodeLabels map[string]string `json:"nodeLabels,omitempty"`
	// Taints is used to add user defined Kubernetes taints to all nodes in the new node pool.
	// These taints are applied to the Kubernetes API node object and can be used in tolerations for pod scheduling.
	Taints []TaintConfigApplyConfiguration `json:"taints,omitempty"`
	// ConfidentialNodeType: Defines the type of technology used by the
	// confidential node.
	//
	// Possible values:
	// "CONFIDENTIAL_INSTANCE_TYPE_UNSPECIFIED" - No type specified. Do not use
	// this value.
	// "SEV" - AMD Secure Encrypted Virtualization.
	// "SEV_SNP" - AMD Secure Encrypted Virtualization - Secure Nested Paging.
	// "TDX" - Intel Trust Domain eXtension.
	ConfidentialNodeType *string `json:"confidentialNodeType,omitempty"`
	// AutoRepair if set to true specifies that a node pool should have auto repair enabled, disabled in case of being set to false.
	AutoRepair *bool `json:"autoRepair,omitempty"`
	// AutoUpgrade if set to true specifies that a node pool should have auto upgrade enabled, disabled in case of being set to false.
	AutoUpgrade *bool `json:"autoUpgrade,omitempty"`
	// ImageStreaming contains image streaming settings.
	ImageStreaming *ImageStreamingApplyConfiguration `json:"imageStreaming,omitempty"`
	// ResourceManagerTags defines what existing GCE resource manager tag key/value pairs
	// with purpose GCE_FIREWALL to attach to all node pools.
	// Referenced Tags must be created beforehand via Resource Manager API.
	ResourceManagerTags []TagsApplyConfiguration `json:"resourceManagerTags,omitempty"`
	// Gvnic contains Google Virtual NIC settings.
	Gvnic *GvnicApplyConfiguration `json:"gvnic,omitempty"`
	// Contains logging configuration.
	LoggingConfig *NodePoolLoggingConfigApplyConfiguration `json:"loggingConfig,omitempty"`
	// Dra describes settings related to dynamic resource allocation
	// and its integration with autoprovisioning
	Dra *DraApplyConfiguration `json:"dra,omitempty"`
	// IPType specifies whether the nodes in the node pool use public or private IP addresses.
	// Possible values are "public" or "private".
	// An empty string indicates the default IP type.
	// This setting corresponds to the presence and value of the cloud.google.com/private-node node selector.
	IPType *string `json:"ipType,omitempty"`
	// NodeVersion defines the GKE version to be used for the node pool.
	// If unspecified, the GKE cluster server will automatically pick a version
	// as per https://cloud.google.com/kubernetes-engine/versioning#specifying_node_version.
	NodeVersion *string `json:"nodeVersion,omitempty"`
	// Tpu defines node pool configuration for Google TPU.
	Tpu *GoogleTpuApplyConfiguration `json:"tpu,omitempty"`
	// Sandbox contains sandbox configuration.
	Sandbox *SandboxApplyConfiguration `json:"sandbox,omitempty"`
	// WorkloadMetadata specifies how node metadata is exposed to the workload.
	// Possible values are "GCE_METADATA" or "GKE_METADATA".
	WorkloadMetadata *string `json:"workloadMetadata,omitempty"`
	// InstanceMetadata is a map of custom key-value pairs to be injected into the underlying Compute Engine instances.
	InstanceMetadata map[string]string `json:"instanceMetadata,omitempty"`
	// TaintConfig contains node pool taint configuration.
	TaintConfig *NodePoolTaintConfigApplyConfiguration `json:"taintConfig,omitempty"`
	// MaintenanceExclusion defines the type of exclusion policy applied to node pools.
	// UNTIL_END_OF_SUPPORT - will not be upgraded until end of support of the nodepool's minor version
	MaintenanceExclusion *cloudgooglecomv1.MaintenanceExclusionType `json:"maintenanceExclusion,omitempty"`
	// Custom node image configuration used by nodes in the node pool.
	CustomImageConfig *CustomImageConfigApplyConfiguration `json:"customImageConfig,omitempty"`
}

// NodePoolConfigApplyConfiguration constructs a declarative configuration of the NodePoolConfig type for use with
// apply.
func NodePoolConfig() *NodePoolConfigApplyConfiguration {
	return &NodePoolConfigApplyConfiguration{}
}

// WithServiceAccount sets the ServiceAccount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccount field is set to the value of the last call.
func (b *NodePoolConfigApplyConfiguration) WithServiceAccount(value string) *NodePoolConfigApplyConfiguration {
	b.ServiceAccount = &value
	return b
}

// WithImageType sets the ImageType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageType field is set to the value of the last call.
func (b *NodePoolConfigApplyConfiguration) WithImageType(value string) *NodePoolConfigApplyConfiguration {
	b.ImageType = &value
	return b
}

// WithWorkloadType sets the WorkloadType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkloadType field is set to the value of the last call.
func (b *NodePoolConfigApplyConfiguration) WithWorkloadType(value string) *NodePoolConfigApplyConfiguration {
	b.WorkloadType = &value
	return b
}

// WithNodeLabels puts the entries into the NodeLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeLabels field,
// overwriting an existing map entries in NodeLabels field with the same key.
func (b *NodePoolConfigApplyConfiguration) WithNodeLabels(entries map[string]string) *NodePoolConfigApplyConfiguration {
	if b.NodeLabels == nil && len(entries) > 0 {
		b.NodeLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeLabels[k] = v
	}
	return b
}

// WithTaints adds the given value to the Taints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Taints field.
func (b *NodePoolConfigApplyConfiguration) WithTaints(values ...*TaintConfigApplyConfiguration) *NodePoolConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTaints")
		}
		b.Taints = append(b.Taints, *values[i])
	}
	return b
}

// WithConfidentialNodeType sets the ConfidentialNodeType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfidentialNodeType field is set to the value of the last call.
func (b *NodePoolConfigApplyConfiguration) WithConfidentialNodeType(value string) *NodePoolConfigApplyConfiguration {
	b.ConfidentialNodeType = &value
	return b
}

// WithAutoRepair sets the AutoRepair field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutoRepair field is set to the value of the last call.
func (b *NodePoolConfigApplyConfiguration) WithAutoRepair(value bool) *NodePoolConfigApplyConfiguration {
	b.AutoRepair = &value
	return b
}

// WithAutoUpgrade sets the AutoUpgrade field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutoUpgrade field is set to the value of the last call.
func (b *NodePoolConfigApplyConfiguration) WithAutoUpgrade(value bool) *NodePoolConfigApplyConfiguration {
	b.AutoUpgrade = &value
	return b
}

// WithImageStreaming sets the ImageStreaming field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageStreaming field is set to the value of the last call.
func (b *NodePoolConfigApplyConfiguration) WithImageStreaming(value *ImageStreamingApplyConfiguration) *NodePoolConfigApplyConfiguration {
	b.ImageStreaming = value
	return b
}

// WithResourceManagerTags adds the given value to the ResourceManagerTags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ResourceManagerTags field.
func (b *NodePoolConfigApplyConfiguration) WithResourceManagerTags(values ...*TagsApplyConfiguration) *NodePoolConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithResourceManagerTags")
		}
		b.ResourceManagerTags = append(b.ResourceManagerTags, *values[i])
	}
	return b
}

// WithGvnic sets the Gvnic field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Gvnic field is set to the value of the last call.
func (b *NodePoolConfigApplyConfiguration) WithGvnic(value *GvnicApplyConfiguration) *NodePoolConfigApplyConfiguration {
	b.Gvnic = value
	return b
}

// WithLoggingConfig sets the LoggingConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LoggingConfig field is set to the value of the last call.
func (b *NodePoolConfigApplyConfiguration) WithLoggingConfig(value *NodePoolLoggingConfigApplyConfiguration) *NodePoolConfigApplyConfiguration {
	b.LoggingConfig = value
	return b
}

// WithDra sets the Dra field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Dra field is set to the value of the last call.
func (b *NodePoolConfigApplyConfiguration) WithDra(value *DraApplyConfiguration) *NodePoolConfigApplyConfiguration {
	b.Dra = value
	return b
}

// WithIPType sets the IPType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPType field is set to the value of the last call.
func (b *NodePoolConfigApplyConfiguration) WithIPType(value string) *NodePoolConfigApplyConfiguration {
	b.IPType = &value
	return b
}

// WithNodeVersion sets the NodeVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeVersion field is set to the value of the last call.
func (b *NodePoolConfigApplyConfiguration) WithNodeVersion(value string) *NodePoolConfigApplyConfiguration {
	b.NodeVersion = &value
	return b
}

// WithTpu sets the Tpu field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tpu field is set to the value of the last call.
func (b *NodePoolConfigApplyConfiguration) WithTpu(value *GoogleTpuApplyConfiguration) *NodePoolConfigApplyConfiguration {
	b.Tpu = value
	return b
}

// WithSandbox sets the Sandbox field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Sandbox field is set to the value of the last call.
func (b *NodePoolConfigApplyConfiguration) WithSandbox(value *SandboxApplyConfiguration) *NodePoolConfigApplyConfiguration {
	b.Sandbox = value
	return b
}

// WithWorkloadMetadata sets the WorkloadMetadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkloadMetadata field is set to the value of the last call.
func (b *NodePoolConfigApplyConfiguration) WithWorkloadMetadata(value string) *NodePoolConfigApplyConfiguration {
	b.WorkloadMetadata = &value
	return b
}

// WithInstanceMetadata puts the entries into the InstanceMetadata field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the InstanceMetadata field,
// overwriting an existing map entries in InstanceMetadata field with the same key.
func (b *NodePoolConfigApplyConfiguration) WithInstanceMetadata(entries map[string]string) *NodePoolConfigApplyConfiguration {
	if b.InstanceMetadata == nil && len(entries) > 0 {
		b.InstanceMetadata = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.InstanceMetadata[k] = v
	}
	return b
}

// WithTaintConfig sets the TaintConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TaintConfig field is set to the value of the last call.
func (b *NodePoolConfigApplyConfiguration) WithTaintConfig(value *NodePoolTaintConfigApplyConfiguration) *NodePoolConfigApplyConfiguration {
	b.TaintConfig = value
	return b
}

// WithMaintenanceExclusion sets the MaintenanceExclusion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaintenanceExclusion field is set to the value of the last call.
func (b *NodePoolConfigApplyConfiguration) WithMaintenanceExclusion(value cloudgooglecomv1.MaintenanceExclusionType) *NodePoolConfigApplyConfiguration {
	b.MaintenanceExclusion = &value
	return b
}

// WithCustomImageConfig sets the CustomImageConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomImageConfig field is set to the value of the last call.
func (b *NodePoolConfigApplyConfiguration) WithCustomImageConfig(value *CustomImageConfigApplyConfiguration) *NodePoolConfigApplyConfiguration {
	b.CustomImageConfig = value
	return b
}
