/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// NodePoolAutoCreationApplyConfiguration represents a declarative configuration of the NodePoolAutoCreation type for use
// with apply.
//
// NodePoolAutoCreation defines node-pool autoprovisioning related settings.
type NodePoolAutoCreationApplyConfiguration struct {
	// Enabled indicates whether NodePoolAutoCreation is enabled for a given ComputeClass.
	Enabled *bool `json:"enabled,omitempty"`
	// DynamicMaxPodsPerNode if set to true specifies that max pods per node value for managed node pools will be selected
	// by Cluster Autoscaler automatically, based on the binpacking simulation results. It is ignored if there is a Priority.MaxPodsPerNode value specified.
	// If not specified the value defaults to being true for Compute Classes with Autopilot enabled.
	// If set to false cluster wide static value for max pods per node is used.
	DynamicMaxPodsPerNode *bool `json:"dynamicMaxPodsPerNode,omitempty"`
	// DynamicBootDiskSize if set to true specifies that boot disk size value for managed node pools will be selected
	// by Cluster Autoscaler automatically, based on the binpacking simulation results. It is ignored if there is a Priority.Storage.BootDiskSize value specified.
	// If not specified the value defaults to being true for Compute Classes with Autopilot enabled.
	// If set to false cluster wide static value from AutoprovisioningNodePoolDefaults is used.
	DynamicBootDiskSize *bool `json:"dynamicBootDiskSize,omitempty"`
	// ShieldedInstanceConfig defines the shielded instance configuration for auto-created node pools.
	ShieldedInstanceConfig *ShieldedInstanceConfigApplyConfiguration `json:"shieldedInstanceConfig,omitempty"`
}

// NodePoolAutoCreationApplyConfiguration constructs a declarative configuration of the NodePoolAutoCreation type for use with
// apply.
func NodePoolAutoCreation() *NodePoolAutoCreationApplyConfiguration {
	return &NodePoolAutoCreationApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *NodePoolAutoCreationApplyConfiguration) WithEnabled(value bool) *NodePoolAutoCreationApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithDynamicMaxPodsPerNode sets the DynamicMaxPodsPerNode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DynamicMaxPodsPerNode field is set to the value of the last call.
func (b *NodePoolAutoCreationApplyConfiguration) WithDynamicMaxPodsPerNode(value bool) *NodePoolAutoCreationApplyConfiguration {
	b.DynamicMaxPodsPerNode = &value
	return b
}

// WithDynamicBootDiskSize sets the DynamicBootDiskSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DynamicBootDiskSize field is set to the value of the last call.
func (b *NodePoolAutoCreationApplyConfiguration) WithDynamicBootDiskSize(value bool) *NodePoolAutoCreationApplyConfiguration {
	b.DynamicBootDiskSize = &value
	return b
}

// WithShieldedInstanceConfig sets the ShieldedInstanceConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ShieldedInstanceConfig field is set to the value of the last call.
func (b *NodePoolAutoCreationApplyConfiguration) WithShieldedInstanceConfig(value *ShieldedInstanceConfigApplyConfiguration) *NodePoolAutoCreationApplyConfiguration {
	b.ShieldedInstanceConfig = value
	return b
}
