/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// NodeVfioConfigApplyConfiguration represents a declarative configuration of the NodeVfioConfig type for use
// with apply.
//
// NodeVfioConfig defines configuration settings for VFIO on a node.
type NodeVfioConfigApplyConfiguration struct {
	// Specifies the maximum number of DMA entries (pages) that can be mapped
	// by the VFIO IOMMU type 1 driver for a container. This limit affects the
	// total amount of host memory that can be pinned for direct device access,
	// which is often critical for high-performance devices like TPUs and GPUs.
	// This setting corresponds to the kernel parameter at:
	// /sys/module/vfio_iommu_type1/parameters/dma_entry_limit
	// The default value in the kernel is 65535. Higher values may be
	// needed for workloads mapping large memory regions.
	DmaEntryLimit *int32 `json:"dmaEntryLimit,omitempty"`
}

// NodeVfioConfigApplyConfiguration constructs a declarative configuration of the NodeVfioConfig type for use with
// apply.
func NodeVfioConfig() *NodeVfioConfigApplyConfiguration {
	return &NodeVfioConfigApplyConfiguration{}
}

// WithDmaEntryLimit sets the DmaEntryLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DmaEntryLimit field is set to the value of the last call.
func (b *NodeVfioConfigApplyConfiguration) WithDmaEntryLimit(value int32) *NodeVfioConfigApplyConfiguration {
	b.DmaEntryLimit = &value
	return b
}
