/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	cloudgooglecomv1 "github.com/googlecloudplatform/compute-class-api/api/cloud.google.com/v1"
)

// PriorityApplyConfiguration represents a declarative configuration of the Priority type for use
// with apply.
//
// Priority is a specification of preferred machine characteristics.
type PriorityApplyConfiguration struct {
	// Machine family describes preferred instance family for a node. If none is specified,
	// the default autoprovisioning machine family is used.
	MachineFamily *string `json:"machineFamily,omitempty"`
	// Spot if set to true specifies that a node should be a spot instance, on-demand otherwise.
	Spot *bool `json:"spot,omitempty"`
	// MinCores describes a minimum number of CPU cores of a node.
	MinCores *int `json:"minCores,omitempty"`
	// MinMemoryGb describes a minimum GBs of memory of a node.
	MinMemoryGb *int `json:"minMemoryGb,omitempty"`
	// Nodepools describes preference of specific, preexisting nodepools.
	Nodepools []string `json:"nodepools,omitempty"`
	// Storage describes storage config of a node.
	Storage *StorageApplyConfiguration `json:"storage,omitempty"`
	// MachineType defines preferred machine type for a node.
	MachineType *string `json:"machineType,omitempty"`
	// Gpu defines preferred GPU config for a node.
	Gpu *GPUApplyConfiguration `json:"gpu,omitempty"`
	// Tpu defines preferred TPU config for a node.
	Tpu *TPUApplyConfiguration `json:"tpu,omitempty"`
	// Reservations defines reservations config for a node.
	Reservations *ReservationsApplyConfiguration `json:"reservations,omitempty"`
	// MaxRunDurationSeconds defines the maximum duration for the nodes to exist. If unspecified, the nodes can exist indefinitely.
	MaxRunDurationSeconds *int `json:"maxRunDurationSeconds,omitempty"`
	// MaxPodsPerNode describes the maximum number of pods a node can accommodate.
	MaxPodsPerNode *int `json:"maxPodsPerNode,omitempty"`
	// NodeSystemConfig defines node system config for a node.
	NodeSystemConfig *NodeSystemConfigApplyConfiguration `json:"nodeSystemConfig,omitempty"`
	// FlexStart defines Flex Start provisioning model.
	FlexStart *FlexStartApplyConfiguration `json:"flexStart,omitempty"`
	// PodFamily represents pod-based provisioning and billing config.
	PodFamily *string `json:"podFamily,omitempty"`
	// Location describes CCC zonal preferences config.
	Location *LocationApplyConfiguration `json:"location,omitempty"`
	// Placement defines resource policy used for BYOPP and BYOWP
	Placement *PlacementApplyConfiguration `json:"placement,omitempty"`
	// CapacityCheckWaitTimeSeconds defines for how long will this priority be attempted to scale up before moving on to the next priority.
	CapacityCheckWaitTimeSeconds *int `json:"capacityCheckWaitTimeSeconds,omitempty"`
	// MinCpuPlatform defines the minimum CPU platform for a node.
	MinCpuPlatform *string `json:"minCpuPlatform,omitempty"`
	// NodeLabels is used to add user defined Kubernetes labels to all nodes in the new node pool.
	// These labels are applied to the Kubernetes API node object and can be used in nodeSelectors for pod scheduling.
	// Note: Node labels are distinct from GKE labels.
	// More info: https://cloud.google.com/sdk/gcloud/reference/container/node-pools/create#--node-labels
	NodeLabels map[string]string `json:"nodeLabels,omitempty"`
	// Taints is used to add user defined Kubernetes taints to all nodes in the new node pool.
	// These taints are applied to the Kubernetes API node object and can be used in tolerations for pod scheduling.
	Taints []TaintConfigApplyConfiguration `json:"taints,omitempty"`
	// A higher value is treated as a higher priority.
	// Priorities with the same priorityScore value are treated equally.
	// Not more than 3 priorities can have the same priorityScore.
	PriorityScore *int `json:"priorityScore,omitempty"`
	// AcceleratorNetworkProfile defines the type of automated accelerator network provisioning to use.
	// Possible values:
	// "auto": Enables automatic ANP configuration based on the machine type.
	// "auto-<suffix>": Enables automatic ANP with a custom network profile suffix.
	AcceleratorNetworkProfile *string `json:"acceleratorNetworkProfile,omitempty"`
	// GpuDirect defines the gpu direct strategy.
	// Possible values:
	// "rdma"
	GpuDirect *string `json:"gpuDirect,omitempty"`
	// MinimumCapacity defines declarative minimum node preprovisioning requirements
	// for this specific priority.
	MinimumCapacity *MinimumCapacityApplyConfiguration `json:"minimumCapacity,omitempty"`
	// InstanceMetadata is a map of custom key-value pairs to be injected into the underlying Compute Engine instances.
	// Overrides conflicting keys defined in NodePoolConfig.InstanceMetadata.
	InstanceMetadata map[string]string `json:"instanceMetadata,omitempty"`
	// AllocationStrategy defines the allocation strategy for a node pool.
	AllocationStrategy *cloudgooglecomv1.AllocationStrategy `json:"allocationStrategy,omitempty"`
}

// PriorityApplyConfiguration constructs a declarative configuration of the Priority type for use with
// apply.
func Priority() *PriorityApplyConfiguration {
	return &PriorityApplyConfiguration{}
}

// WithMachineFamily sets the MachineFamily field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MachineFamily field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithMachineFamily(value string) *PriorityApplyConfiguration {
	b.MachineFamily = &value
	return b
}

// WithSpot sets the Spot field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spot field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithSpot(value bool) *PriorityApplyConfiguration {
	b.Spot = &value
	return b
}

// WithMinCores sets the MinCores field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinCores field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithMinCores(value int) *PriorityApplyConfiguration {
	b.MinCores = &value
	return b
}

// WithMinMemoryGb sets the MinMemoryGb field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinMemoryGb field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithMinMemoryGb(value int) *PriorityApplyConfiguration {
	b.MinMemoryGb = &value
	return b
}

// WithNodepools adds the given value to the Nodepools field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Nodepools field.
func (b *PriorityApplyConfiguration) WithNodepools(values ...string) *PriorityApplyConfiguration {
	for i := range values {
		b.Nodepools = append(b.Nodepools, values[i])
	}
	return b
}

// WithStorage sets the Storage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Storage field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithStorage(value *StorageApplyConfiguration) *PriorityApplyConfiguration {
	b.Storage = value
	return b
}

// WithMachineType sets the MachineType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MachineType field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithMachineType(value string) *PriorityApplyConfiguration {
	b.MachineType = &value
	return b
}

// WithGpu sets the Gpu field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Gpu field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithGpu(value *GPUApplyConfiguration) *PriorityApplyConfiguration {
	b.Gpu = value
	return b
}

// WithTpu sets the Tpu field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tpu field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithTpu(value *TPUApplyConfiguration) *PriorityApplyConfiguration {
	b.Tpu = value
	return b
}

// WithReservations sets the Reservations field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reservations field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithReservations(value *ReservationsApplyConfiguration) *PriorityApplyConfiguration {
	b.Reservations = value
	return b
}

// WithMaxRunDurationSeconds sets the MaxRunDurationSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxRunDurationSeconds field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithMaxRunDurationSeconds(value int) *PriorityApplyConfiguration {
	b.MaxRunDurationSeconds = &value
	return b
}

// WithMaxPodsPerNode sets the MaxPodsPerNode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxPodsPerNode field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithMaxPodsPerNode(value int) *PriorityApplyConfiguration {
	b.MaxPodsPerNode = &value
	return b
}

// WithNodeSystemConfig sets the NodeSystemConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeSystemConfig field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithNodeSystemConfig(value *NodeSystemConfigApplyConfiguration) *PriorityApplyConfiguration {
	b.NodeSystemConfig = value
	return b
}

// WithFlexStart sets the FlexStart field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FlexStart field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithFlexStart(value *FlexStartApplyConfiguration) *PriorityApplyConfiguration {
	b.FlexStart = value
	return b
}

// WithPodFamily sets the PodFamily field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodFamily field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithPodFamily(value string) *PriorityApplyConfiguration {
	b.PodFamily = &value
	return b
}

// WithLocation sets the Location field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Location field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithLocation(value *LocationApplyConfiguration) *PriorityApplyConfiguration {
	b.Location = value
	return b
}

// WithPlacement sets the Placement field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Placement field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithPlacement(value *PlacementApplyConfiguration) *PriorityApplyConfiguration {
	b.Placement = value
	return b
}

// WithCapacityCheckWaitTimeSeconds sets the CapacityCheckWaitTimeSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CapacityCheckWaitTimeSeconds field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithCapacityCheckWaitTimeSeconds(value int) *PriorityApplyConfiguration {
	b.CapacityCheckWaitTimeSeconds = &value
	return b
}

// WithMinCpuPlatform sets the MinCpuPlatform field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinCpuPlatform field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithMinCpuPlatform(value string) *PriorityApplyConfiguration {
	b.MinCpuPlatform = &value
	return b
}

// WithNodeLabels puts the entries into the NodeLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeLabels field,
// overwriting an existing map entries in NodeLabels field with the same key.
func (b *PriorityApplyConfiguration) WithNodeLabels(entries map[string]string) *PriorityApplyConfiguration {
	if b.NodeLabels == nil && len(entries) > 0 {
		b.NodeLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeLabels[k] = v
	}
	return b
}

// WithTaints adds the given value to the Taints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Taints field.
func (b *PriorityApplyConfiguration) WithTaints(values ...*TaintConfigApplyConfiguration) *PriorityApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTaints")
		}
		b.Taints = append(b.Taints, *values[i])
	}
	return b
}

// WithPriorityScore sets the PriorityScore field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PriorityScore field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithPriorityScore(value int) *PriorityApplyConfiguration {
	b.PriorityScore = &value
	return b
}

// WithAcceleratorNetworkProfile sets the AcceleratorNetworkProfile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AcceleratorNetworkProfile field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithAcceleratorNetworkProfile(value string) *PriorityApplyConfiguration {
	b.AcceleratorNetworkProfile = &value
	return b
}

// WithGpuDirect sets the GpuDirect field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GpuDirect field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithGpuDirect(value string) *PriorityApplyConfiguration {
	b.GpuDirect = &value
	return b
}

// WithMinimumCapacity sets the MinimumCapacity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinimumCapacity field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithMinimumCapacity(value *MinimumCapacityApplyConfiguration) *PriorityApplyConfiguration {
	b.MinimumCapacity = value
	return b
}

// WithInstanceMetadata puts the entries into the InstanceMetadata field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the InstanceMetadata field,
// overwriting an existing map entries in InstanceMetadata field with the same key.
func (b *PriorityApplyConfiguration) WithInstanceMetadata(entries map[string]string) *PriorityApplyConfiguration {
	if b.InstanceMetadata == nil && len(entries) > 0 {
		b.InstanceMetadata = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.InstanceMetadata[k] = v
	}
	return b
}

// WithAllocationStrategy sets the AllocationStrategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllocationStrategy field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithAllocationStrategy(value cloudgooglecomv1.AllocationStrategy) *PriorityApplyConfiguration {
	b.AllocationStrategy = &value
	return b
}
