/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// PriorityApplyConfiguration represents an declarative configuration of the Priority type for use
// with apply.
type PriorityApplyConfiguration struct {
	MachineFamily *string  `json:"machineFamily,omitempty"`
	Spot          *bool    `json:"spot,omitempty"`
	MinCores      *int     `json:"minCores,omitempty"`
	MinMemoryGb   *int     `json:"minMemoryGb,omitempty"`
	Nodepools     []string `json:"nodepools,omitempty"`
}

// PriorityApplyConfiguration constructs an declarative configuration of the Priority type for use with
// apply.
func Priority() *PriorityApplyConfiguration {
	return &PriorityApplyConfiguration{}
}

// WithMachineFamily sets the MachineFamily field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MachineFamily field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithMachineFamily(value string) *PriorityApplyConfiguration {
	b.MachineFamily = &value
	return b
}

// WithSpot sets the Spot field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spot field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithSpot(value bool) *PriorityApplyConfiguration {
	b.Spot = &value
	return b
}

// WithMinCores sets the MinCores field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinCores field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithMinCores(value int) *PriorityApplyConfiguration {
	b.MinCores = &value
	return b
}

// WithMinMemoryGb sets the MinMemoryGb field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinMemoryGb field is set to the value of the last call.
func (b *PriorityApplyConfiguration) WithMinMemoryGb(value int) *PriorityApplyConfiguration {
	b.MinMemoryGb = &value
	return b
}

// WithNodepools adds the given value to the Nodepools field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Nodepools field.
func (b *PriorityApplyConfiguration) WithNodepools(values ...string) *PriorityApplyConfiguration {
	for i := range values {
		b.Nodepools = append(b.Nodepools, values[i])
	}
	return b
}
