/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	cloudgooglecomv1 "github.com/googlecloudplatform/compute-class-api/api/cloud.google.com/v1"
)

// PrivateRegistryAccessConfigApplyConfiguration represents a declarative configuration of the PrivateRegistryAccessConfig type for use
// with apply.
//
// PrivateRegistryAccessConfig defines access configuration for private container registries.
type PrivateRegistryAccessConfigApplyConfiguration struct {
	// Enabled is a boolean flag to enable or disable private registry access.
	Enabled *bool `json:"enabled,omitempty"`
	// CertificateAuthorityDomainConfig configures domain-specific certificate authorities for secure communication with private registries.
	CertificateAuthorityDomainConfig []*cloudgooglecomv1.CertificateAuthorityDomainConfig `json:"certificateAuthorityDomainConfig,omitempty"`
}

// PrivateRegistryAccessConfigApplyConfiguration constructs a declarative configuration of the PrivateRegistryAccessConfig type for use with
// apply.
func PrivateRegistryAccessConfig() *PrivateRegistryAccessConfigApplyConfiguration {
	return &PrivateRegistryAccessConfigApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *PrivateRegistryAccessConfigApplyConfiguration) WithEnabled(value bool) *PrivateRegistryAccessConfigApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithCertificateAuthorityDomainConfig adds the given value to the CertificateAuthorityDomainConfig field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CertificateAuthorityDomainConfig field.
func (b *PrivateRegistryAccessConfigApplyConfiguration) WithCertificateAuthorityDomainConfig(values ...**cloudgooglecomv1.CertificateAuthorityDomainConfig) *PrivateRegistryAccessConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCertificateAuthorityDomainConfig")
		}
		b.CertificateAuthorityDomainConfig = append(b.CertificateAuthorityDomainConfig, *values[i])
	}
	return b
}
