/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	cloudgooglecomv1 "github.com/googlecloudplatform/compute-class-api/api/cloud.google.com/v1"
)

// ReconciliationPolicyApplyConfiguration represents a declarative configuration of the ReconciliationPolicy type for use
// with apply.
//
// ReconciliationPolicy describes how nodes should be migrated.
type ReconciliationPolicyApplyConfiguration struct {
	// Strategy defines the migration strategy to use.
	// It is only applicable to config drift active migration.
	// Optimize rule priority and ensure all daemon set pods running always use CreateBeforeDelete.
	// Supported values:
	// * CreateBeforeDelete
	// * DeleteBeforeCreate
	Strategy *cloudgooglecomv1.MigrationStrategy `json:"strategy,omitempty"`
	// MaxNodeDisruption defines the maximum number of nodes that can be deleted at the same time during drift migration.
	MaxNodeDisruption *int32 `json:"maxNodeDisruption,omitempty"`
	// AtomicGroupLabels defines a list of node label keys used to group drifted nodes.
	// Nodes are only grouped together if they share the exact same values for ALL specified labels.
	AtomicGroupLabels []string `json:"atomicGroupLabels,omitempty"`
}

// ReconciliationPolicyApplyConfiguration constructs a declarative configuration of the ReconciliationPolicy type for use with
// apply.
func ReconciliationPolicy() *ReconciliationPolicyApplyConfiguration {
	return &ReconciliationPolicyApplyConfiguration{}
}

// WithStrategy sets the Strategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Strategy field is set to the value of the last call.
func (b *ReconciliationPolicyApplyConfiguration) WithStrategy(value cloudgooglecomv1.MigrationStrategy) *ReconciliationPolicyApplyConfiguration {
	b.Strategy = &value
	return b
}

// WithMaxNodeDisruption sets the MaxNodeDisruption field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxNodeDisruption field is set to the value of the last call.
func (b *ReconciliationPolicyApplyConfiguration) WithMaxNodeDisruption(value int32) *ReconciliationPolicyApplyConfiguration {
	b.MaxNodeDisruption = &value
	return b
}

// WithAtomicGroupLabels adds the given value to the AtomicGroupLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AtomicGroupLabels field.
func (b *ReconciliationPolicyApplyConfiguration) WithAtomicGroupLabels(values ...string) *ReconciliationPolicyApplyConfiguration {
	for i := range values {
		b.AtomicGroupLabels = append(b.AtomicGroupLabels, values[i])
	}
	return b
}
