/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	cloudgooglecomv1 "github.com/googlecloudplatform/compute-class-api/api/cloud.google.com/v1"
)

// RegistryHostConfigApplyConfiguration represents a declarative configuration of the RegistryHostConfig type for use
// with apply.
//
// RegistryHostConfig defines containerd registry host configuration.
type RegistryHostConfigApplyConfiguration struct {
	// Server is the FQDN of the primary registry server.
	Server *string `json:"server,omitempty"`
	// Hosts is the list of host configs for the registry server.
	Hosts []*cloudgooglecomv1.HostConfig `json:"hosts,omitempty"`
}

// RegistryHostConfigApplyConfiguration constructs a declarative configuration of the RegistryHostConfig type for use with
// apply.
func RegistryHostConfig() *RegistryHostConfigApplyConfiguration {
	return &RegistryHostConfigApplyConfiguration{}
}

// WithServer sets the Server field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Server field is set to the value of the last call.
func (b *RegistryHostConfigApplyConfiguration) WithServer(value string) *RegistryHostConfigApplyConfiguration {
	b.Server = &value
	return b
}

// WithHosts adds the given value to the Hosts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Hosts field.
func (b *RegistryHostConfigApplyConfiguration) WithHosts(values ...**cloudgooglecomv1.HostConfig) *RegistryHostConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithHosts")
		}
		b.Hosts = append(b.Hosts, *values[i])
	}
	return b
}
