/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ReservedResourcesConfigApplyConfiguration represents a declarative configuration of the ReservedResourcesConfig type for use
// with apply.
//
// ReservedResourcesConfig contains the configuration for the reserved resources on the node.
type ReservedResourcesConfigApplyConfiguration struct {
	// CpuReservedMillicore is the amount of CPU to reserve for system daemons.
	// This is a user-specified value. If unspecified, GKE decides the default.
	CpuReservedMillicore *int64 `json:"cpuReservedMillicore,omitempty"`
	// MemoryReservedMib is the amount of memory to reserve for system daemons (in MiB).
	// This is a user-specified value. If unspecified, GKE decides the default.
	MemoryReservedMib *int64 `json:"memoryReservedMib,omitempty"`
}

// ReservedResourcesConfigApplyConfiguration constructs a declarative configuration of the ReservedResourcesConfig type for use with
// apply.
func ReservedResourcesConfig() *ReservedResourcesConfigApplyConfiguration {
	return &ReservedResourcesConfigApplyConfiguration{}
}

// WithCpuReservedMillicore sets the CpuReservedMillicore field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CpuReservedMillicore field is set to the value of the last call.
func (b *ReservedResourcesConfigApplyConfiguration) WithCpuReservedMillicore(value int64) *ReservedResourcesConfigApplyConfiguration {
	b.CpuReservedMillicore = &value
	return b
}

// WithMemoryReservedMib sets the MemoryReservedMib field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MemoryReservedMib field is set to the value of the last call.
func (b *ReservedResourcesConfigApplyConfiguration) WithMemoryReservedMib(value int64) *ReservedResourcesConfigApplyConfiguration {
	b.MemoryReservedMib = &value
	return b
}
