/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/googlecloudplatform/compute-class-api/api/cloud.google.com/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ResourceInfoApplyConfiguration represents an declarative configuration of the ResourceInfo type for use
// with apply.
type ResourceInfoApplyConfiguration struct {
	Name                         *v1.ResourceName `json:"name,omitempty"`
	Unit                         *v1.ResourceUnit `json:"unit,omitempty"`
	TargetCount                  *int             `json:"targetCount,omitempty"`
	CurrentCount                 *int             `json:"currentCount,omitempty"`
	CurrentUtilizationPercentage *int             `json:"currentUtilizationPercentage,omitempty"`
	MeasuredAt                   *metav1.Time     `json:"measuredAt,omitempty"`
}

// ResourceInfoApplyConfiguration constructs an declarative configuration of the ResourceInfo type for use with
// apply.
func ResourceInfo() *ResourceInfoApplyConfiguration {
	return &ResourceInfoApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ResourceInfoApplyConfiguration) WithName(value v1.ResourceName) *ResourceInfoApplyConfiguration {
	b.Name = &value
	return b
}

// WithUnit sets the Unit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Unit field is set to the value of the last call.
func (b *ResourceInfoApplyConfiguration) WithUnit(value v1.ResourceUnit) *ResourceInfoApplyConfiguration {
	b.Unit = &value
	return b
}

// WithTargetCount sets the TargetCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetCount field is set to the value of the last call.
func (b *ResourceInfoApplyConfiguration) WithTargetCount(value int) *ResourceInfoApplyConfiguration {
	b.TargetCount = &value
	return b
}

// WithCurrentCount sets the CurrentCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentCount field is set to the value of the last call.
func (b *ResourceInfoApplyConfiguration) WithCurrentCount(value int) *ResourceInfoApplyConfiguration {
	b.CurrentCount = &value
	return b
}

// WithCurrentUtilizationPercentage sets the CurrentUtilizationPercentage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentUtilizationPercentage field is set to the value of the last call.
func (b *ResourceInfoApplyConfiguration) WithCurrentUtilizationPercentage(value int) *ResourceInfoApplyConfiguration {
	b.CurrentUtilizationPercentage = &value
	return b
}

// WithMeasuredAt sets the MeasuredAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MeasuredAt field is set to the value of the last call.
func (b *ResourceInfoApplyConfiguration) WithMeasuredAt(value metav1.Time) *ResourceInfoApplyConfiguration {
	b.MeasuredAt = &value
	return b
}
