/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// StorageApplyConfiguration represents a declarative configuration of the Storage type for use
// with apply.
//
// Storage defines storage config per priority rule.
type StorageApplyConfiguration struct {
	// BootDiskSize defines the size of a disk attached to node, specified in GB.
	BootDiskSize *int `json:"bootDiskSize,omitempty"`
	// BootDiskType defines type of the disk attached to the node.
	// Note that available boot disk types depend on the machine family / machine type selected.
	// Currently supported types:
	// * pd-balanced
	// * pd-standard
	// * pd-ssd
	// * hyperdisk-balanced
	BootDiskType *string `json:"bootDiskType,omitempty"`
	// BootDiskKMSKey defines a key used to encrypt the boot disk attached.
	BootDiskKMSKey *string `json:"bootDiskKMSKey,omitempty"`
	// LocalSSDCount defines a number of local SSDs attached to node.
	LocalSSDCount *int `json:"localSSDCount,omitempty"`
	// SecondaryBootDisks represent persistent disks attached to a node with special configurations based on their modes.
	SecondaryBootDisks []SecondaryBootDiskApplyConfiguration `json:"secondaryBootDisks,omitempty"`
	// BootDiskStoragePools defines a list of storage pools to be used for the boot disk.
	// The resource name must be in the format: projects/{project}/zones/{zone}/storagePools/{storage_pool}.
	BootDiskStoragePools []string `json:"bootDiskStoragePools,omitempty"`
}

// StorageApplyConfiguration constructs a declarative configuration of the Storage type for use with
// apply.
func Storage() *StorageApplyConfiguration {
	return &StorageApplyConfiguration{}
}

// WithBootDiskSize sets the BootDiskSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BootDiskSize field is set to the value of the last call.
func (b *StorageApplyConfiguration) WithBootDiskSize(value int) *StorageApplyConfiguration {
	b.BootDiskSize = &value
	return b
}

// WithBootDiskType sets the BootDiskType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BootDiskType field is set to the value of the last call.
func (b *StorageApplyConfiguration) WithBootDiskType(value string) *StorageApplyConfiguration {
	b.BootDiskType = &value
	return b
}

// WithBootDiskKMSKey sets the BootDiskKMSKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BootDiskKMSKey field is set to the value of the last call.
func (b *StorageApplyConfiguration) WithBootDiskKMSKey(value string) *StorageApplyConfiguration {
	b.BootDiskKMSKey = &value
	return b
}

// WithLocalSSDCount sets the LocalSSDCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocalSSDCount field is set to the value of the last call.
func (b *StorageApplyConfiguration) WithLocalSSDCount(value int) *StorageApplyConfiguration {
	b.LocalSSDCount = &value
	return b
}

// WithSecondaryBootDisks adds the given value to the SecondaryBootDisks field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SecondaryBootDisks field.
func (b *StorageApplyConfiguration) WithSecondaryBootDisks(values ...*SecondaryBootDiskApplyConfiguration) *StorageApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSecondaryBootDisks")
		}
		b.SecondaryBootDisks = append(b.SecondaryBootDisks, *values[i])
	}
	return b
}

// WithBootDiskStoragePools adds the given value to the BootDiskStoragePools field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the BootDiskStoragePools field.
func (b *StorageApplyConfiguration) WithBootDiskStoragePools(values ...string) *StorageApplyConfiguration {
	for i := range values {
		b.BootDiskStoragePools = append(b.BootDiskStoragePools, values[i])
	}
	return b
}
