/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// StorageApplyConfiguration represents an declarative configuration of the Storage type for use
// with apply.
type StorageApplyConfiguration struct {
	BootDiskSize       *int                                  `json:"bootDiskSize,omitempty"`
	BootDiskType       *string                               `json:"bootDiskType,omitempty"`
	BootDiskKMSKey     *string                               `json:"bootDiskKMSKey,omitempty"`
	LocalSSDCount      *int                                  `json:"localSSDCount,omitempty"`
	SecondaryBootDisks []SecondaryBootDiskApplyConfiguration `json:"secondaryBootDisks,omitempty"`
}

// StorageApplyConfiguration constructs an declarative configuration of the Storage type for use with
// apply.
func Storage() *StorageApplyConfiguration {
	return &StorageApplyConfiguration{}
}

// WithBootDiskSize sets the BootDiskSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BootDiskSize field is set to the value of the last call.
func (b *StorageApplyConfiguration) WithBootDiskSize(value int) *StorageApplyConfiguration {
	b.BootDiskSize = &value
	return b
}

// WithBootDiskType sets the BootDiskType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BootDiskType field is set to the value of the last call.
func (b *StorageApplyConfiguration) WithBootDiskType(value string) *StorageApplyConfiguration {
	b.BootDiskType = &value
	return b
}

// WithBootDiskKMSKey sets the BootDiskKMSKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BootDiskKMSKey field is set to the value of the last call.
func (b *StorageApplyConfiguration) WithBootDiskKMSKey(value string) *StorageApplyConfiguration {
	b.BootDiskKMSKey = &value
	return b
}

// WithLocalSSDCount sets the LocalSSDCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocalSSDCount field is set to the value of the last call.
func (b *StorageApplyConfiguration) WithLocalSSDCount(value int) *StorageApplyConfiguration {
	b.LocalSSDCount = &value
	return b
}

// WithSecondaryBootDisks adds the given value to the SecondaryBootDisks field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SecondaryBootDisks field.
func (b *StorageApplyConfiguration) WithSecondaryBootDisks(values ...*SecondaryBootDiskApplyConfiguration) *StorageApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSecondaryBootDisks")
		}
		b.SecondaryBootDisks = append(b.SecondaryBootDisks, *values[i])
	}
	return b
}
