/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// SwapConfigBootDiskProfileApplyConfiguration represents a declarative configuration of the SwapConfigBootDiskProfile type for use
// with apply.
type SwapConfigBootDiskProfileApplyConfiguration struct {
	SwapSizeGib     *int64 `json:"swapSizeGib,omitempty"`
	SwapSizePercent *int32 `json:"swapSizePercent,omitempty"`
}

// SwapConfigBootDiskProfileApplyConfiguration constructs a declarative configuration of the SwapConfigBootDiskProfile type for use with
// apply.
func SwapConfigBootDiskProfile() *SwapConfigBootDiskProfileApplyConfiguration {
	return &SwapConfigBootDiskProfileApplyConfiguration{}
}

// WithSwapSizeGib sets the SwapSizeGib field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SwapSizeGib field is set to the value of the last call.
func (b *SwapConfigBootDiskProfileApplyConfiguration) WithSwapSizeGib(value int64) *SwapConfigBootDiskProfileApplyConfiguration {
	b.SwapSizeGib = &value
	return b
}

// WithSwapSizePercent sets the SwapSizePercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SwapSizePercent field is set to the value of the last call.
func (b *SwapConfigBootDiskProfileApplyConfiguration) WithSwapSizePercent(value int32) *SwapConfigBootDiskProfileApplyConfiguration {
	b.SwapSizePercent = &value
	return b
}
