/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// SwapConfigApplyConfiguration represents a declarative configuration of the SwapConfig type for use
// with apply.
//
// SwapConfig specifies the swap memory configuration for a node pool.
type SwapConfigApplyConfiguration struct {
	// Enables or disables swap for the node pool. Default to false.
	Enabled *bool `json:"enabled,omitempty"`
	// If omitted, swap space is encrypted by default.
	EncryptionConfig *SwapConfigEncryptionConfigApplyConfiguration `json:"encryptionConfig,omitempty"`
	// Use the node's boot disk for swap.
	BootDiskProfile *SwapConfigBootDiskProfileApplyConfiguration `json:"bootDiskProfile,omitempty"`
	// Use the local SSD (shared with ephemeral storage) for swap.
	EphemeralLocalSsdProfile *SwapConfigEphemeralLocalSsdProfileApplyConfiguration `json:"ephemeralLocalSsdProfile,omitempty"`
	// Provision a new, separate local NVMe SSD exclusively for swap.
	DedicatedLocalSsdProfile *SwapConfigDedicatedLocalSsdProfileApplyConfiguration `json:"dedicatedLocalSsdProfile,omitempty"`
}

// SwapConfigApplyConfiguration constructs a declarative configuration of the SwapConfig type for use with
// apply.
func SwapConfig() *SwapConfigApplyConfiguration {
	return &SwapConfigApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *SwapConfigApplyConfiguration) WithEnabled(value bool) *SwapConfigApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithEncryptionConfig sets the EncryptionConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EncryptionConfig field is set to the value of the last call.
func (b *SwapConfigApplyConfiguration) WithEncryptionConfig(value *SwapConfigEncryptionConfigApplyConfiguration) *SwapConfigApplyConfiguration {
	b.EncryptionConfig = value
	return b
}

// WithBootDiskProfile sets the BootDiskProfile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BootDiskProfile field is set to the value of the last call.
func (b *SwapConfigApplyConfiguration) WithBootDiskProfile(value *SwapConfigBootDiskProfileApplyConfiguration) *SwapConfigApplyConfiguration {
	b.BootDiskProfile = value
	return b
}

// WithEphemeralLocalSsdProfile sets the EphemeralLocalSsdProfile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EphemeralLocalSsdProfile field is set to the value of the last call.
func (b *SwapConfigApplyConfiguration) WithEphemeralLocalSsdProfile(value *SwapConfigEphemeralLocalSsdProfileApplyConfiguration) *SwapConfigApplyConfiguration {
	b.EphemeralLocalSsdProfile = value
	return b
}

// WithDedicatedLocalSsdProfile sets the DedicatedLocalSsdProfile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DedicatedLocalSsdProfile field is set to the value of the last call.
func (b *SwapConfigApplyConfiguration) WithDedicatedLocalSsdProfile(value *SwapConfigDedicatedLocalSsdProfileApplyConfiguration) *SwapConfigApplyConfiguration {
	b.DedicatedLocalSsdProfile = value
	return b
}
