/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// SysctlsConfigApplyConfiguration represents a declarative configuration of the SysctlsConfig type for use
// with apply.
//
// SysctlsConfig defines sysctls config for a node.
type SysctlsConfigApplyConfiguration struct {
	// Maximum number of packets, queued on the INPUT side, when the interface receives packets faster than kernel can process them.
	Net_core_netdev_max_backlog *int64 `json:"net.core.netdev_max_backlog,omitempty"`
	// The maximum receive socket buffer size in bytes.
	Net_core_rmem_max *int64 `json:"net.core.rmem_max,omitempty"`
	// The default setting (in bytes) of the socket send buffer.
	Net_core_wmem_default *int64 `json:"net.core.wmem_default,omitempty"`
	// The maximum send socket buffer size in bytes.
	Net_core_wmem_max *int64 `json:"net.core.wmem_max,omitempty"`
	// Maximum ancillary buffer size allowed per socket. Ancillary data is a sequence of struct cmsghdr structures with appended data.
	Net_core_optmem_max *int64 `json:"net.core.optmem_max,omitempty"`
	// Limit of socket listen() backlog, known in userspace as SOMAXCONN. Defaults to 128. See also tcp_max_syn_backlog for additional tuning for TCP sockets.
	Net_core_somaxconn *int64 `json:"net.core.somaxconn,omitempty"`
	// Minimal size of receive buffer used by UDP sockets in moderation. Each UDP socket is able to use the size for receiving data, even if total pages of UDP sockets exceed udp_mem pressure. The unit is byte. Default: 1 page. The three values are: min, default, max. Eg. '4096 87380 6291456'.
	Net_ipv4_tcp_rmem *string `json:"net.ipv4.tcp_rmem,omitempty"`
	// Minimal size of send buffer used by UDP sockets in moderation. Each UDP socket is able to use the size for sending data, even if total pages of UDP sockets exceed udp_mem pressure. The unit is byte. Default: 1 page. The three values are: min, default, max. Eg. '4096 87380 6291456'.
	Net_ipv4_tcp_wmem *string `json:"net.ipv4.tcp_wmem,omitempty"`
	// Allow to reuse TIME-WAIT sockets for new connections when it is safe from protocol viewpoint. It should not be changed without advice/request of technical experts.
	Net_ipv4_tcp_tw_reuse *int64 `json:"net.ipv4.tcp_tw_reuse,omitempty"`
	// Low latency busy poll timeout for poll and select. (needs CONFIG_NET_RX_BUSY_POLL) Approximate time in us to busy loop waiting for events.
	Net_core_busy_poll *int64 `json:"net.core.busy_poll,omitempty"`
	// Low latency busy poll timeout for socket reads. (needs CONFIG_NET_RX_BUSY_POLL) Approximate time in us to busy loop waiting for packets on the device queue.
	Net_core_busy_read *int64 `json:"net.core.busy_read,omitempty"`
	// Changing this value is same as changing conf/default/disable_ipv6 setting and also all per-interface disable_ipv6 settings to the same value.
	Net_ipv6_conf_all_disable_ipv6 *bool `json:"net.ipv6.conf.all.disable_ipv6,omitempty"`
	// Disable IPv6 operation.
	Net_ipv6_conf_default_disable_ipv6 *bool `json:"net.ipv6.conf.default.disable_ipv6,omitempty"`
	// Maximum number of memory map areas a process may have.
	Vm_max_map_count *int64 `json:"vm.max_map_count,omitempty"`
	// The system-wide maximum number of shared memory segments.
	Kernel_shmmni *int64 `json:"kernel.shmmni,omitempty"`
	// The maximum size (in bytes) of a single shared memory segment allowed by the kernel.
	// Note that the actual range should be integer between 0 and 18446744073692774399, while kubebuilder would lose some precision on uint64 during the internal representation and parsing.
	Kernel_shmall *string `json:"kernel.shmall,omitempty"`
	// The total amount of shared memory pages that can be used on the system at one time.
	// Note that the actual range should be integer between 0 and 18446744073692774399, while kubebuilder would lose some precision on uint64 during the internal representation and parsing.
	Kernel_shmmax *string `json:"kernel.shmmax,omitempty"`
	// The default receive socket buffer size in bytes.
	Net_core_rmem_default *int64 `json:"net.core.rmem_default,omitempty"`
	// The size of connection tracking table.
	Net_netfilter_nf_conntrack_max *int64 `json:"net.netfilter.nf_conntrack_max,omitempty"`
	// The size of hash table for connection tracking.
	Net_netfilter_nf_conntrack_buckets *int64 `json:"net.netfilter.nf_conntrack_buckets,omitempty"`
	// Whether to enable connection tracking flow accounting.
	Net_netfilter_nf_conntrack_acct *bool `json:"net.netfilter.nf_conntrack_acct,omitempty"`
	// The duration of dead connections before deleted automatically from connection tracking table.
	Net_netfilter_nf_conntrack_tcp_timeout_established *int64 `json:"net.netfilter.nf_conntrack_tcp_timeout_established,omitempty"`
	// The period for which the TCP connections can remain in the CLOSE_WAIT state, and stay in the table.
	Net_netfilter_nf_conntrack_tcp_timeout_close_wait *int64 `json:"net.netfilter.nf_conntrack_tcp_timeout_close_wait,omitempty"`
	// The period for which the TCP connections can remain in the TIME_WAIT state, and stay in the table.
	Net_netfilter_nf_conntrack_tcp_timeout_time_wait *int64 `json:"net.netfilter.nf_conntrack_tcp_timeout_time_wait,omitempty"`
	// The maximum number of file descriptors that can be opened by a process.
	Fs_nr_open *int64 `json:"fs.nr_open,omitempty"`
	// The maximum number of inotify watches that a user can create.
	Fs_inotify_max_user_watches *int64 `json:"fs.inotify.max_user_watches,omitempty"`
	// The maximum number of inotify instances that a user can create.
	Fs_inotify_max_user_instances *int64 `json:"fs.inotify.max_user_instances,omitempty"`
	// Determines the kernel's memory overcommit handling strategy.
	// Supported values:
	// 0: Rejects allocations that are obviously too large.
	// 1: Allows overcommit until memory is exhausted.
	// 2 (strict): Prevents overcommit beyond swap space plus a percentage of RAM defined by 'vm.overcommit_ratio'.
	Vm_overcommit_memory *int64 `json:"vm.overcommit_memory,omitempty"`
	// Specifies the percentage of physical RAM allowed for overcommit when 'vm.overcommit_memory' is set to 2.
	// The total committed address space cannot exceed swap plus this RAM percentage.
	Vm_overcommit_ratio *int64 `json:"vm.overcommit_ratio,omitempty"`
	// Adjusts the kernel's preference for reclaiming memory used for dentry (directory) and inode caches.
	Vm_vfs_cache_pressure *int64 `json:"vm.vfs_cache_pressure,omitempty"`
	// Percentage of system memory that can be filled with dirty pages (modified but not yet written to disk) before background kernel flusher threads begin writeback.
	// This value should be less than 'vm.dirty_ratio'.
	Vm_dirty_background_ratio *int64 `json:"vm.dirty_background_ratio,omitempty"`
	// Percentage of system memory that can be filled with dirty pages before processes performing writes are forced to block and write out dirty data synchronously.
	// This value should be greater than 'vm.dirty_background_ratio'.
	Vm_dirty_ratio *int64 `json:"vm.dirty_ratio,omitempty"`
	// Maximum age (in hundredths of a second) that dirty data can remain in memory before kernel flusher threads write it to disk.
	// Lower values result in faster, more frequent writebacks.
	Vm_dirty_expire_centisecs *int64 `json:"vm.dirty_expire_centisecs,omitempty"`
	// Interval (in hundredths of a second) at which kernel flusher threads wake up to write 'old' dirty data to disk.
	Vm_dirty_writeback_centisecs *int64 `json:"vm.dirty_writeback_centisecs,omitempty"`
	// Maximum number of file-handles that the Linux kernel will allocate.
	Fs_file_max *int64 `json:"fs.file-max,omitempty"`
	// The maximum system-wide number of asynchronous io requests.
	Fs_aio_max_nr             *int64 `json:"fs.aio-max-nr,omitempty"`
	Net_ipv4_tcp_max_orphans  *int64 `json:"net.ipv4.tcp_max_orphans,omitempty"`
	Vm_swappiness             *int64 `json:"vm.swappiness,omitempty"`
	Vm_watermark_scale_factor *int64 `json:"vm.watermark_scale_factor,omitempty"`
	Vm_min_free_kbytes        *int64 `json:"vm.min_free_kbytes,omitempty"`
	// Controls TCP Packetization-Layer Path MTU Discovery. Supported values:
	// 0: Disabled
	// 1: Disabled by default, enabled when an ICMP black hole detected
	// 2: Always enabled, use initial MSS of tcp_base_mss.
	Net_ipv4_tcp_mtu_probing *int64 `json:"net.ipv4.tcp_mtu_probing,omitempty"`
	// Maximal number of timewait sockets held by system simultaneously. If this number is exceeded time-wait socket is immediately destroyed and warning is printed.
	Net_ipv4_tcp_max_tw_buckets *int64 `json:"net.ipv4.tcp_max_tw_buckets,omitempty"`
	// Number of times initial SYNs for an active TCP connection attempt will be retransmitted.
	Net_ipv4_tcp_syn_retries *int64 `json:"net.ipv4.tcp_syn_retries,omitempty"`
	// Control use of Explicit Congestion Notification (ECN) by TCP. ECN is used only when both ends of the TCP connection indicate support for it.
	Net_ipv4_tcp_ecn *int64 `json:"net.ipv4.tcp_ecn,omitempty"`
	// Set the congestion control algorithm to be used for new connections. The algorithm “reno” is always available, but additional choices may be available based on kernel configuration. Default is set as part of kernel configuration. For passive connections, the listener congestion control choice is inherited.
	Net_ipv4_tcp_congestion_control *string `json:"net.ipv4.tcp_congestion_control,omitempty"`
	// Controls use of the performance events system by unprivileged users (without CAP_PERFMON). The default value is 2 in kernel.
	Kernel_perf_event_paranoid *int64 `json:"kernel.perf_event_paranoid,omitempty"`
	// A global limit on how much time real-time scheduling may use.
	Kernel_sched_rt_runtime_us *int64 `json:"kernel.sched_rt_runtime_us,omitempty"`
	// Control whether the kernel panics when a soft lockup is detected.
	Kernel_softlockup_panic *bool `json:"kernel.softlockup_panic,omitempty"`
	// Defines the scope and restrictions for the ptrace() system call, impacting process debugging and tracing. Supported values:
	// 0: Classic ptrace permissions.
	// 1: Restricted ptrace (default in many distributions) - only child processes or CAP_SYS_PTRACE.
	// 2: Admin-only ptrace - only processes with CAP_SYS_PTRACE.
	// 3: No ptrace - ptrace calls are disallowed.
	Kernel_yama_ptrace_scope *int64 `json:"kernel.yama.ptrace_scope,omitempty"`
	// Indicates whether restrictions are placed on exposing kernel addresses via /proc and other interfaces.
	Kernel_kptr_restrict *int64 `json:"kernel.kptr_restrict,omitempty"`
	// Indicates whether unprivileged users are prevented from using dmesg(8) to view messages from the kernel’s log buffer.
	Kernel_dmesg_restrict *bool `json:"kernel.dmesg_restrict,omitempty"`
	// Controls the functions allowed to be invoked via the SysRq key. List of possible values:
	// 0: Disables sysrq completely.
	// 1: Enables all sysrq functions.
	// >1 - bitmask of allowed sysrq functions. More details in https://docs.kernel.org/admin-guide/sysrq.html.
	Kernel_sysrq *int64 `json:"kernel.sysrq,omitempty"`
	// Contains the amount of dirty memory at which the background kernel flusher threads will start writeback.
	// Note: Vm_dirty_background_bytes is the counterpart of Vm_dirty_background_ratio. Only one of them may be specified at a time.
	Vm_dirty_background_bytes *int64 `json:"vm.dirty_background_bytes,omitempty"`
	// Contains the amount of dirty memory at which a process generating disk writes will itself start writeback.
	// Note: Vm_dirty_bytes is the counterpart of Vm_dirty_ratio. Only one of them may be specified at a time.
	// Note: the minimum value allowed for Vm_dirty_bytes is two pages (in bytes); any value lower than this limit will be ignored and the old configuration will be retained.
	Vm_dirty_bytes *int64 `json:"vm.dirty_bytes,omitempty"`
	// Defines the core dump pattern for the kernel.
	// Only absolute paths are supported. Piping and relative paths are not allowed.
	Kernel_core_pattern *string `json:"kernel.core_pattern,omitempty"`
	// Controls the maximum number of keys that a nonroot user may own.
	Kernel_keys_maxkeys *int64 `json:"kernel.keys.maxkeys,omitempty"`
	// Represents the maximum number of bytes that a nonroot user can hold in the payload section of all their keys.
	Kernel_keys_maxbytes *int64 `json:"kernel.keys.maxbytes,omitempty"`
	// Tells the garbage collector the minimum number of network entries that can sit in cache (floor).
	Net_ipv4_neigh_default_gc_thresh1 *int64 `json:"net.ipv4.neigh.default.gc_thresh1,omitempty"`
	// Acts as a soft limit to the number of network device entries stored in cache (soft ceiling).
	Net_ipv4_neigh_default_gc_thresh2 *int64 `json:"net.ipv4.neigh.default.gc_thresh2,omitempty"`
	// Sets a hard ceiling (absolute maximum) for the network neighbor cache.
	Net_ipv4_neigh_default_gc_thresh3 *int64 `json:"net.ipv4.neigh.default.gc_thresh3,omitempty"`
}

// SysctlsConfigApplyConfiguration constructs a declarative configuration of the SysctlsConfig type for use with
// apply.
func SysctlsConfig() *SysctlsConfigApplyConfiguration {
	return &SysctlsConfigApplyConfiguration{}
}

// WithNet_core_netdev_max_backlog sets the Net_core_netdev_max_backlog field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_core_netdev_max_backlog field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_core_netdev_max_backlog(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_core_netdev_max_backlog = &value
	return b
}

// WithNet_core_rmem_max sets the Net_core_rmem_max field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_core_rmem_max field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_core_rmem_max(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_core_rmem_max = &value
	return b
}

// WithNet_core_wmem_default sets the Net_core_wmem_default field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_core_wmem_default field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_core_wmem_default(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_core_wmem_default = &value
	return b
}

// WithNet_core_wmem_max sets the Net_core_wmem_max field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_core_wmem_max field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_core_wmem_max(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_core_wmem_max = &value
	return b
}

// WithNet_core_optmem_max sets the Net_core_optmem_max field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_core_optmem_max field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_core_optmem_max(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_core_optmem_max = &value
	return b
}

// WithNet_core_somaxconn sets the Net_core_somaxconn field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_core_somaxconn field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_core_somaxconn(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_core_somaxconn = &value
	return b
}

// WithNet_ipv4_tcp_rmem sets the Net_ipv4_tcp_rmem field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_ipv4_tcp_rmem field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_ipv4_tcp_rmem(value string) *SysctlsConfigApplyConfiguration {
	b.Net_ipv4_tcp_rmem = &value
	return b
}

// WithNet_ipv4_tcp_wmem sets the Net_ipv4_tcp_wmem field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_ipv4_tcp_wmem field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_ipv4_tcp_wmem(value string) *SysctlsConfigApplyConfiguration {
	b.Net_ipv4_tcp_wmem = &value
	return b
}

// WithNet_ipv4_tcp_tw_reuse sets the Net_ipv4_tcp_tw_reuse field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_ipv4_tcp_tw_reuse field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_ipv4_tcp_tw_reuse(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_ipv4_tcp_tw_reuse = &value
	return b
}

// WithNet_core_busy_poll sets the Net_core_busy_poll field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_core_busy_poll field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_core_busy_poll(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_core_busy_poll = &value
	return b
}

// WithNet_core_busy_read sets the Net_core_busy_read field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_core_busy_read field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_core_busy_read(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_core_busy_read = &value
	return b
}

// WithNet_ipv6_conf_all_disable_ipv6 sets the Net_ipv6_conf_all_disable_ipv6 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_ipv6_conf_all_disable_ipv6 field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_ipv6_conf_all_disable_ipv6(value bool) *SysctlsConfigApplyConfiguration {
	b.Net_ipv6_conf_all_disable_ipv6 = &value
	return b
}

// WithNet_ipv6_conf_default_disable_ipv6 sets the Net_ipv6_conf_default_disable_ipv6 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_ipv6_conf_default_disable_ipv6 field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_ipv6_conf_default_disable_ipv6(value bool) *SysctlsConfigApplyConfiguration {
	b.Net_ipv6_conf_default_disable_ipv6 = &value
	return b
}

// WithVm_max_map_count sets the Vm_max_map_count field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vm_max_map_count field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithVm_max_map_count(value int64) *SysctlsConfigApplyConfiguration {
	b.Vm_max_map_count = &value
	return b
}

// WithKernel_shmmni sets the Kernel_shmmni field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kernel_shmmni field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithKernel_shmmni(value int64) *SysctlsConfigApplyConfiguration {
	b.Kernel_shmmni = &value
	return b
}

// WithKernel_shmall sets the Kernel_shmall field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kernel_shmall field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithKernel_shmall(value string) *SysctlsConfigApplyConfiguration {
	b.Kernel_shmall = &value
	return b
}

// WithKernel_shmmax sets the Kernel_shmmax field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kernel_shmmax field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithKernel_shmmax(value string) *SysctlsConfigApplyConfiguration {
	b.Kernel_shmmax = &value
	return b
}

// WithNet_core_rmem_default sets the Net_core_rmem_default field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_core_rmem_default field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_core_rmem_default(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_core_rmem_default = &value
	return b
}

// WithNet_netfilter_nf_conntrack_max sets the Net_netfilter_nf_conntrack_max field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_netfilter_nf_conntrack_max field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_netfilter_nf_conntrack_max(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_netfilter_nf_conntrack_max = &value
	return b
}

// WithNet_netfilter_nf_conntrack_buckets sets the Net_netfilter_nf_conntrack_buckets field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_netfilter_nf_conntrack_buckets field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_netfilter_nf_conntrack_buckets(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_netfilter_nf_conntrack_buckets = &value
	return b
}

// WithNet_netfilter_nf_conntrack_acct sets the Net_netfilter_nf_conntrack_acct field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_netfilter_nf_conntrack_acct field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_netfilter_nf_conntrack_acct(value bool) *SysctlsConfigApplyConfiguration {
	b.Net_netfilter_nf_conntrack_acct = &value
	return b
}

// WithNet_netfilter_nf_conntrack_tcp_timeout_established sets the Net_netfilter_nf_conntrack_tcp_timeout_established field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_netfilter_nf_conntrack_tcp_timeout_established field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_netfilter_nf_conntrack_tcp_timeout_established(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_netfilter_nf_conntrack_tcp_timeout_established = &value
	return b
}

// WithNet_netfilter_nf_conntrack_tcp_timeout_close_wait sets the Net_netfilter_nf_conntrack_tcp_timeout_close_wait field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_netfilter_nf_conntrack_tcp_timeout_close_wait field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_netfilter_nf_conntrack_tcp_timeout_close_wait(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_netfilter_nf_conntrack_tcp_timeout_close_wait = &value
	return b
}

// WithNet_netfilter_nf_conntrack_tcp_timeout_time_wait sets the Net_netfilter_nf_conntrack_tcp_timeout_time_wait field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_netfilter_nf_conntrack_tcp_timeout_time_wait field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_netfilter_nf_conntrack_tcp_timeout_time_wait(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_netfilter_nf_conntrack_tcp_timeout_time_wait = &value
	return b
}

// WithFs_nr_open sets the Fs_nr_open field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Fs_nr_open field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithFs_nr_open(value int64) *SysctlsConfigApplyConfiguration {
	b.Fs_nr_open = &value
	return b
}

// WithFs_inotify_max_user_watches sets the Fs_inotify_max_user_watches field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Fs_inotify_max_user_watches field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithFs_inotify_max_user_watches(value int64) *SysctlsConfigApplyConfiguration {
	b.Fs_inotify_max_user_watches = &value
	return b
}

// WithFs_inotify_max_user_instances sets the Fs_inotify_max_user_instances field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Fs_inotify_max_user_instances field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithFs_inotify_max_user_instances(value int64) *SysctlsConfigApplyConfiguration {
	b.Fs_inotify_max_user_instances = &value
	return b
}

// WithVm_overcommit_memory sets the Vm_overcommit_memory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vm_overcommit_memory field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithVm_overcommit_memory(value int64) *SysctlsConfigApplyConfiguration {
	b.Vm_overcommit_memory = &value
	return b
}

// WithVm_overcommit_ratio sets the Vm_overcommit_ratio field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vm_overcommit_ratio field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithVm_overcommit_ratio(value int64) *SysctlsConfigApplyConfiguration {
	b.Vm_overcommit_ratio = &value
	return b
}

// WithVm_vfs_cache_pressure sets the Vm_vfs_cache_pressure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vm_vfs_cache_pressure field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithVm_vfs_cache_pressure(value int64) *SysctlsConfigApplyConfiguration {
	b.Vm_vfs_cache_pressure = &value
	return b
}

// WithVm_dirty_background_ratio sets the Vm_dirty_background_ratio field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vm_dirty_background_ratio field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithVm_dirty_background_ratio(value int64) *SysctlsConfigApplyConfiguration {
	b.Vm_dirty_background_ratio = &value
	return b
}

// WithVm_dirty_ratio sets the Vm_dirty_ratio field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vm_dirty_ratio field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithVm_dirty_ratio(value int64) *SysctlsConfigApplyConfiguration {
	b.Vm_dirty_ratio = &value
	return b
}

// WithVm_dirty_expire_centisecs sets the Vm_dirty_expire_centisecs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vm_dirty_expire_centisecs field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithVm_dirty_expire_centisecs(value int64) *SysctlsConfigApplyConfiguration {
	b.Vm_dirty_expire_centisecs = &value
	return b
}

// WithVm_dirty_writeback_centisecs sets the Vm_dirty_writeback_centisecs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vm_dirty_writeback_centisecs field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithVm_dirty_writeback_centisecs(value int64) *SysctlsConfigApplyConfiguration {
	b.Vm_dirty_writeback_centisecs = &value
	return b
}

// WithFs_file_max sets the Fs_file_max field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Fs_file_max field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithFs_file_max(value int64) *SysctlsConfigApplyConfiguration {
	b.Fs_file_max = &value
	return b
}

// WithFs_aio_max_nr sets the Fs_aio_max_nr field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Fs_aio_max_nr field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithFs_aio_max_nr(value int64) *SysctlsConfigApplyConfiguration {
	b.Fs_aio_max_nr = &value
	return b
}

// WithNet_ipv4_tcp_max_orphans sets the Net_ipv4_tcp_max_orphans field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_ipv4_tcp_max_orphans field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_ipv4_tcp_max_orphans(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_ipv4_tcp_max_orphans = &value
	return b
}

// WithVm_swappiness sets the Vm_swappiness field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vm_swappiness field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithVm_swappiness(value int64) *SysctlsConfigApplyConfiguration {
	b.Vm_swappiness = &value
	return b
}

// WithVm_watermark_scale_factor sets the Vm_watermark_scale_factor field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vm_watermark_scale_factor field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithVm_watermark_scale_factor(value int64) *SysctlsConfigApplyConfiguration {
	b.Vm_watermark_scale_factor = &value
	return b
}

// WithVm_min_free_kbytes sets the Vm_min_free_kbytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vm_min_free_kbytes field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithVm_min_free_kbytes(value int64) *SysctlsConfigApplyConfiguration {
	b.Vm_min_free_kbytes = &value
	return b
}

// WithNet_ipv4_tcp_mtu_probing sets the Net_ipv4_tcp_mtu_probing field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_ipv4_tcp_mtu_probing field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_ipv4_tcp_mtu_probing(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_ipv4_tcp_mtu_probing = &value
	return b
}

// WithNet_ipv4_tcp_max_tw_buckets sets the Net_ipv4_tcp_max_tw_buckets field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_ipv4_tcp_max_tw_buckets field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_ipv4_tcp_max_tw_buckets(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_ipv4_tcp_max_tw_buckets = &value
	return b
}

// WithNet_ipv4_tcp_syn_retries sets the Net_ipv4_tcp_syn_retries field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_ipv4_tcp_syn_retries field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_ipv4_tcp_syn_retries(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_ipv4_tcp_syn_retries = &value
	return b
}

// WithNet_ipv4_tcp_ecn sets the Net_ipv4_tcp_ecn field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_ipv4_tcp_ecn field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_ipv4_tcp_ecn(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_ipv4_tcp_ecn = &value
	return b
}

// WithNet_ipv4_tcp_congestion_control sets the Net_ipv4_tcp_congestion_control field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_ipv4_tcp_congestion_control field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_ipv4_tcp_congestion_control(value string) *SysctlsConfigApplyConfiguration {
	b.Net_ipv4_tcp_congestion_control = &value
	return b
}

// WithKernel_perf_event_paranoid sets the Kernel_perf_event_paranoid field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kernel_perf_event_paranoid field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithKernel_perf_event_paranoid(value int64) *SysctlsConfigApplyConfiguration {
	b.Kernel_perf_event_paranoid = &value
	return b
}

// WithKernel_sched_rt_runtime_us sets the Kernel_sched_rt_runtime_us field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kernel_sched_rt_runtime_us field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithKernel_sched_rt_runtime_us(value int64) *SysctlsConfigApplyConfiguration {
	b.Kernel_sched_rt_runtime_us = &value
	return b
}

// WithKernel_softlockup_panic sets the Kernel_softlockup_panic field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kernel_softlockup_panic field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithKernel_softlockup_panic(value bool) *SysctlsConfigApplyConfiguration {
	b.Kernel_softlockup_panic = &value
	return b
}

// WithKernel_yama_ptrace_scope sets the Kernel_yama_ptrace_scope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kernel_yama_ptrace_scope field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithKernel_yama_ptrace_scope(value int64) *SysctlsConfigApplyConfiguration {
	b.Kernel_yama_ptrace_scope = &value
	return b
}

// WithKernel_kptr_restrict sets the Kernel_kptr_restrict field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kernel_kptr_restrict field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithKernel_kptr_restrict(value int64) *SysctlsConfigApplyConfiguration {
	b.Kernel_kptr_restrict = &value
	return b
}

// WithKernel_dmesg_restrict sets the Kernel_dmesg_restrict field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kernel_dmesg_restrict field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithKernel_dmesg_restrict(value bool) *SysctlsConfigApplyConfiguration {
	b.Kernel_dmesg_restrict = &value
	return b
}

// WithKernel_sysrq sets the Kernel_sysrq field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kernel_sysrq field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithKernel_sysrq(value int64) *SysctlsConfigApplyConfiguration {
	b.Kernel_sysrq = &value
	return b
}

// WithVm_dirty_background_bytes sets the Vm_dirty_background_bytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vm_dirty_background_bytes field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithVm_dirty_background_bytes(value int64) *SysctlsConfigApplyConfiguration {
	b.Vm_dirty_background_bytes = &value
	return b
}

// WithVm_dirty_bytes sets the Vm_dirty_bytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vm_dirty_bytes field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithVm_dirty_bytes(value int64) *SysctlsConfigApplyConfiguration {
	b.Vm_dirty_bytes = &value
	return b
}

// WithKernel_core_pattern sets the Kernel_core_pattern field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kernel_core_pattern field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithKernel_core_pattern(value string) *SysctlsConfigApplyConfiguration {
	b.Kernel_core_pattern = &value
	return b
}

// WithKernel_keys_maxkeys sets the Kernel_keys_maxkeys field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kernel_keys_maxkeys field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithKernel_keys_maxkeys(value int64) *SysctlsConfigApplyConfiguration {
	b.Kernel_keys_maxkeys = &value
	return b
}

// WithKernel_keys_maxbytes sets the Kernel_keys_maxbytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kernel_keys_maxbytes field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithKernel_keys_maxbytes(value int64) *SysctlsConfigApplyConfiguration {
	b.Kernel_keys_maxbytes = &value
	return b
}

// WithNet_ipv4_neigh_default_gc_thresh1 sets the Net_ipv4_neigh_default_gc_thresh1 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_ipv4_neigh_default_gc_thresh1 field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_ipv4_neigh_default_gc_thresh1(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_ipv4_neigh_default_gc_thresh1 = &value
	return b
}

// WithNet_ipv4_neigh_default_gc_thresh2 sets the Net_ipv4_neigh_default_gc_thresh2 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_ipv4_neigh_default_gc_thresh2 field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_ipv4_neigh_default_gc_thresh2(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_ipv4_neigh_default_gc_thresh2 = &value
	return b
}

// WithNet_ipv4_neigh_default_gc_thresh3 sets the Net_ipv4_neigh_default_gc_thresh3 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_ipv4_neigh_default_gc_thresh3 field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_ipv4_neigh_default_gc_thresh3(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_ipv4_neigh_default_gc_thresh3 = &value
	return b
}
