/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// SysctlsConfigApplyConfiguration represents an declarative configuration of the SysctlsConfig type for use
// with apply.
type SysctlsConfigApplyConfiguration struct {
	Net_core_netdev_max_backlog                        *int64  `json:"net.core.netdev_max_backlog,omitempty"`
	Net_core_rmem_max                                  *int64  `json:"net.core.rmem_max,omitempty"`
	Net_core_wmem_default                              *int64  `json:"net.core.wmem_default,omitempty"`
	Net_core_wmem_max                                  *int64  `json:"net.core.wmem_max,omitempty"`
	Net_core_optmem_max                                *int64  `json:"net.core.optmem_max,omitempty"`
	Net_core_somaxconn                                 *int64  `json:"net.core.somaxconn,omitempty"`
	Net_ipv4_tcp_rmem                                  *string `json:"net.ipv4.tcp_rmem,omitempty"`
	Net_ipv4_tcp_wmem                                  *string `json:"net.ipv4.tcp_wmem,omitempty"`
	Net_ipv4_tcp_tw_reuse                              *int64  `json:"net.ipv4.tcp_tw_reuse,omitempty"`
	Net_core_busy_poll                                 *int64  `json:"net.core.busy_poll,omitempty"`
	Net_core_busy_read                                 *int64  `json:"net.core.busy_read,omitempty"`
	Net_ipv6_conf_all_disable_ipv6                     *bool   `json:"net.ipv6.conf.all.disable_ipv6,omitempty"`
	Net_ipv6_conf_default_disable_ipv6                 *bool   `json:"net.ipv6.conf.default.disable_ipv6,omitempty"`
	Vm_max_map_count                                   *int64  `json:"vm.max_map_count,omitempty"`
	Kernel_shmmni                                      *int64  `json:"kernel.shmmni,omitempty"`
	Kernel_shmall                                      *string `json:"kernel.shmall,omitempty"`
	Kernel_shmmax                                      *string `json:"kernel.shmmax,omitempty"`
	Net_core_rmem_default                              *int64  `json:"net.core.rmem_default,omitempty"`
	Net_netfilter_nf_conntrack_max                     *int64  `json:"net.netfilter.nf_conntrack_max,omitempty"`
	Net_netfilter_nf_conntrack_buckets                 *int64  `json:"net.netfilter.nf_conntrack_buckets,omitempty"`
	Net_netfilter_nf_conntrack_acct                    *bool   `json:"net.netfilter.nf_conntrack_acct,omitempty"`
	Net_netfilter_nf_conntrack_tcp_timeout_established *int64  `json:"net.netfilter.nf_conntrack_tcp_timeout_established,omitempty"`
	Net_netfilter_nf_conntrack_tcp_timeout_close_wait  *int64  `json:"net.netfilter.nf_conntrack_tcp_timeout_close_wait,omitempty"`
	Net_netfilter_nf_conntrack_tcp_timeout_time_wait   *int64  `json:"net.netfilter.nf_conntrack_tcp_timeout_time_wait,omitempty"`
	Fs_nr_open                                         *int64  `json:"fs.nr_open,omitempty"`
	Fs_inotify_max_user_watches                        *int64  `json:"fs.inotify.max_user_watches,omitempty"`
	Fs_inotify_max_user_instances                      *int64  `json:"fs.inotify.max_user_instances,omitempty"`
	Vm_overcommit_memory                               *int64  `json:"vm.overcommit_memory,omitempty"`
	Vm_overcommit_ratio                                *int64  `json:"vm.overcommit_ratio,omitempty"`
	Vm_vfs_cache_pressure                              *int64  `json:"vm.vfs_cache_pressure,omitempty"`
	Vm_dirty_background_ratio                          *int64  `json:"vm.dirty_background_ratio,omitempty"`
	Vm_dirty_ratio                                     *int64  `json:"vm.dirty_ratio,omitempty"`
	Vm_dirty_expire_centisecs                          *int64  `json:"vm.dirty_expire_centisecs,omitempty"`
	Vm_dirty_writeback_centisecs                       *int64  `json:"vm.dirty_writeback_centisecs,omitempty"`
	Fs_file_max                                        *int64  `json:"fs.file-max,omitempty"`
	Fs_aio_max_nr                                      *int64  `json:"fs.aio-max-nr,omitempty"`
}

// SysctlsConfigApplyConfiguration constructs an declarative configuration of the SysctlsConfig type for use with
// apply.
func SysctlsConfig() *SysctlsConfigApplyConfiguration {
	return &SysctlsConfigApplyConfiguration{}
}

// WithNet_core_netdev_max_backlog sets the Net_core_netdev_max_backlog field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_core_netdev_max_backlog field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_core_netdev_max_backlog(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_core_netdev_max_backlog = &value
	return b
}

// WithNet_core_rmem_max sets the Net_core_rmem_max field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_core_rmem_max field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_core_rmem_max(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_core_rmem_max = &value
	return b
}

// WithNet_core_wmem_default sets the Net_core_wmem_default field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_core_wmem_default field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_core_wmem_default(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_core_wmem_default = &value
	return b
}

// WithNet_core_wmem_max sets the Net_core_wmem_max field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_core_wmem_max field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_core_wmem_max(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_core_wmem_max = &value
	return b
}

// WithNet_core_optmem_max sets the Net_core_optmem_max field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_core_optmem_max field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_core_optmem_max(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_core_optmem_max = &value
	return b
}

// WithNet_core_somaxconn sets the Net_core_somaxconn field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_core_somaxconn field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_core_somaxconn(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_core_somaxconn = &value
	return b
}

// WithNet_ipv4_tcp_rmem sets the Net_ipv4_tcp_rmem field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_ipv4_tcp_rmem field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_ipv4_tcp_rmem(value string) *SysctlsConfigApplyConfiguration {
	b.Net_ipv4_tcp_rmem = &value
	return b
}

// WithNet_ipv4_tcp_wmem sets the Net_ipv4_tcp_wmem field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_ipv4_tcp_wmem field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_ipv4_tcp_wmem(value string) *SysctlsConfigApplyConfiguration {
	b.Net_ipv4_tcp_wmem = &value
	return b
}

// WithNet_ipv4_tcp_tw_reuse sets the Net_ipv4_tcp_tw_reuse field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_ipv4_tcp_tw_reuse field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_ipv4_tcp_tw_reuse(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_ipv4_tcp_tw_reuse = &value
	return b
}

// WithNet_core_busy_poll sets the Net_core_busy_poll field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_core_busy_poll field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_core_busy_poll(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_core_busy_poll = &value
	return b
}

// WithNet_core_busy_read sets the Net_core_busy_read field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_core_busy_read field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_core_busy_read(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_core_busy_read = &value
	return b
}

// WithNet_ipv6_conf_all_disable_ipv6 sets the Net_ipv6_conf_all_disable_ipv6 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_ipv6_conf_all_disable_ipv6 field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_ipv6_conf_all_disable_ipv6(value bool) *SysctlsConfigApplyConfiguration {
	b.Net_ipv6_conf_all_disable_ipv6 = &value
	return b
}

// WithNet_ipv6_conf_default_disable_ipv6 sets the Net_ipv6_conf_default_disable_ipv6 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_ipv6_conf_default_disable_ipv6 field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_ipv6_conf_default_disable_ipv6(value bool) *SysctlsConfigApplyConfiguration {
	b.Net_ipv6_conf_default_disable_ipv6 = &value
	return b
}

// WithVm_max_map_count sets the Vm_max_map_count field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vm_max_map_count field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithVm_max_map_count(value int64) *SysctlsConfigApplyConfiguration {
	b.Vm_max_map_count = &value
	return b
}

// WithKernel_shmmni sets the Kernel_shmmni field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kernel_shmmni field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithKernel_shmmni(value int64) *SysctlsConfigApplyConfiguration {
	b.Kernel_shmmni = &value
	return b
}

// WithKernel_shmall sets the Kernel_shmall field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kernel_shmall field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithKernel_shmall(value string) *SysctlsConfigApplyConfiguration {
	b.Kernel_shmall = &value
	return b
}

// WithKernel_shmmax sets the Kernel_shmmax field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kernel_shmmax field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithKernel_shmmax(value string) *SysctlsConfigApplyConfiguration {
	b.Kernel_shmmax = &value
	return b
}

// WithNet_core_rmem_default sets the Net_core_rmem_default field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_core_rmem_default field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_core_rmem_default(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_core_rmem_default = &value
	return b
}

// WithNet_netfilter_nf_conntrack_max sets the Net_netfilter_nf_conntrack_max field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_netfilter_nf_conntrack_max field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_netfilter_nf_conntrack_max(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_netfilter_nf_conntrack_max = &value
	return b
}

// WithNet_netfilter_nf_conntrack_buckets sets the Net_netfilter_nf_conntrack_buckets field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_netfilter_nf_conntrack_buckets field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_netfilter_nf_conntrack_buckets(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_netfilter_nf_conntrack_buckets = &value
	return b
}

// WithNet_netfilter_nf_conntrack_acct sets the Net_netfilter_nf_conntrack_acct field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_netfilter_nf_conntrack_acct field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_netfilter_nf_conntrack_acct(value bool) *SysctlsConfigApplyConfiguration {
	b.Net_netfilter_nf_conntrack_acct = &value
	return b
}

// WithNet_netfilter_nf_conntrack_tcp_timeout_established sets the Net_netfilter_nf_conntrack_tcp_timeout_established field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_netfilter_nf_conntrack_tcp_timeout_established field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_netfilter_nf_conntrack_tcp_timeout_established(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_netfilter_nf_conntrack_tcp_timeout_established = &value
	return b
}

// WithNet_netfilter_nf_conntrack_tcp_timeout_close_wait sets the Net_netfilter_nf_conntrack_tcp_timeout_close_wait field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_netfilter_nf_conntrack_tcp_timeout_close_wait field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_netfilter_nf_conntrack_tcp_timeout_close_wait(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_netfilter_nf_conntrack_tcp_timeout_close_wait = &value
	return b
}

// WithNet_netfilter_nf_conntrack_tcp_timeout_time_wait sets the Net_netfilter_nf_conntrack_tcp_timeout_time_wait field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Net_netfilter_nf_conntrack_tcp_timeout_time_wait field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithNet_netfilter_nf_conntrack_tcp_timeout_time_wait(value int64) *SysctlsConfigApplyConfiguration {
	b.Net_netfilter_nf_conntrack_tcp_timeout_time_wait = &value
	return b
}

// WithFs_nr_open sets the Fs_nr_open field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Fs_nr_open field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithFs_nr_open(value int64) *SysctlsConfigApplyConfiguration {
	b.Fs_nr_open = &value
	return b
}

// WithFs_inotify_max_user_watches sets the Fs_inotify_max_user_watches field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Fs_inotify_max_user_watches field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithFs_inotify_max_user_watches(value int64) *SysctlsConfigApplyConfiguration {
	b.Fs_inotify_max_user_watches = &value
	return b
}

// WithFs_inotify_max_user_instances sets the Fs_inotify_max_user_instances field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Fs_inotify_max_user_instances field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithFs_inotify_max_user_instances(value int64) *SysctlsConfigApplyConfiguration {
	b.Fs_inotify_max_user_instances = &value
	return b
}

// WithVm_overcommit_memory sets the Vm_overcommit_memory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vm_overcommit_memory field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithVm_overcommit_memory(value int64) *SysctlsConfigApplyConfiguration {
	b.Vm_overcommit_memory = &value
	return b
}

// WithVm_overcommit_ratio sets the Vm_overcommit_ratio field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vm_overcommit_ratio field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithVm_overcommit_ratio(value int64) *SysctlsConfigApplyConfiguration {
	b.Vm_overcommit_ratio = &value
	return b
}

// WithVm_vfs_cache_pressure sets the Vm_vfs_cache_pressure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vm_vfs_cache_pressure field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithVm_vfs_cache_pressure(value int64) *SysctlsConfigApplyConfiguration {
	b.Vm_vfs_cache_pressure = &value
	return b
}

// WithVm_dirty_background_ratio sets the Vm_dirty_background_ratio field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vm_dirty_background_ratio field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithVm_dirty_background_ratio(value int64) *SysctlsConfigApplyConfiguration {
	b.Vm_dirty_background_ratio = &value
	return b
}

// WithVm_dirty_ratio sets the Vm_dirty_ratio field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vm_dirty_ratio field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithVm_dirty_ratio(value int64) *SysctlsConfigApplyConfiguration {
	b.Vm_dirty_ratio = &value
	return b
}

// WithVm_dirty_expire_centisecs sets the Vm_dirty_expire_centisecs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vm_dirty_expire_centisecs field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithVm_dirty_expire_centisecs(value int64) *SysctlsConfigApplyConfiguration {
	b.Vm_dirty_expire_centisecs = &value
	return b
}

// WithVm_dirty_writeback_centisecs sets the Vm_dirty_writeback_centisecs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vm_dirty_writeback_centisecs field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithVm_dirty_writeback_centisecs(value int64) *SysctlsConfigApplyConfiguration {
	b.Vm_dirty_writeback_centisecs = &value
	return b
}

// WithFs_file_max sets the Fs_file_max field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Fs_file_max field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithFs_file_max(value int64) *SysctlsConfigApplyConfiguration {
	b.Fs_file_max = &value
	return b
}

// WithFs_aio_max_nr sets the Fs_aio_max_nr field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Fs_aio_max_nr field is set to the value of the last call.
func (b *SysctlsConfigApplyConfiguration) WithFs_aio_max_nr(value int64) *SysctlsConfigApplyConfiguration {
	b.Fs_aio_max_nr = &value
	return b
}
