/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// TPUApplyConfiguration represents an declarative configuration of the TPU type for use
// with apply.
type TPUApplyConfiguration struct {
	Type     *string `json:"type,omitempty"`
	Count    *int64  `json:"count,omitempty"`
	Topology *string `json:"topology,omitempty"`
}

// TPUApplyConfiguration constructs an declarative configuration of the TPU type for use with
// apply.
func TPU() *TPUApplyConfiguration {
	return &TPUApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *TPUApplyConfiguration) WithType(value string) *TPUApplyConfiguration {
	b.Type = &value
	return b
}

// WithCount sets the Count field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Count field is set to the value of the last call.
func (b *TPUApplyConfiguration) WithCount(value int64) *TPUApplyConfiguration {
	b.Count = &value
	return b
}

// WithTopology sets the Topology field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Topology field is set to the value of the last call.
func (b *TPUApplyConfiguration) WithTopology(value string) *TPUApplyConfiguration {
	b.Topology = &value
	return b
}
