/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1 "github.com/googlecloudplatform/compute-class-api/api/cloud.google.com/v1"
	cloudgooglecomv1 "github.com/googlecloudplatform/compute-class-api/client/applyconfiguration/cloud.google.com/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=cloud.google.com, Version=v1
	case v1.SchemeGroupVersion.WithKind("ActiveMigration"):
		return &cloudgooglecomv1.ActiveMigrationApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Autopilot"):
		return &cloudgooglecomv1.AutopilotApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("AutoscalingPolicy"):
		return &cloudgooglecomv1.AutoscalingPolicyApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ComputeClass"):
		return &cloudgooglecomv1.ComputeClassApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ComputeClassSpec"):
		return &cloudgooglecomv1.ComputeClassSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ComputeClassStatus"):
		return &cloudgooglecomv1.ComputeClassStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("EvictionMinimumReclaim"):
		return &cloudgooglecomv1.EvictionMinimumReclaimApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("EvictionSoft"):
		return &cloudgooglecomv1.EvictionSoftApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("EvictionSoftGracePeriod"):
		return &cloudgooglecomv1.EvictionSoftGracePeriodApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("FlexStart"):
		return &cloudgooglecomv1.FlexStartApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("GPU"):
		return &cloudgooglecomv1.GPUApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("GpuSharing"):
		return &cloudgooglecomv1.GpuSharingApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Gvnic"):
		return &cloudgooglecomv1.GvnicApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("HugepagesConfig"):
		return &cloudgooglecomv1.HugepagesConfigApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ImageStreaming"):
		return &cloudgooglecomv1.ImageStreamingApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("KubeletConfig"):
		return &cloudgooglecomv1.KubeletConfigApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("LinuxNodeConfig"):
		return &cloudgooglecomv1.LinuxNodeConfigApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Location"):
		return &cloudgooglecomv1.LocationApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("LoggingVariantConfig"):
		return &cloudgooglecomv1.LoggingVariantConfigApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("MemoryManager"):
		return &cloudgooglecomv1.MemoryManagerApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("NodePoolAutoCreation"):
		return &cloudgooglecomv1.NodePoolAutoCreationApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("NodePoolConfig"):
		return &cloudgooglecomv1.NodePoolConfigApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("NodePoolGroup"):
		return &cloudgooglecomv1.NodePoolGroupApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("NodePoolLoggingConfig"):
		return &cloudgooglecomv1.NodePoolLoggingConfigApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("NodeRecyclingConfig"):
		return &cloudgooglecomv1.NodeRecyclingConfigApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("NodeSystemConfig"):
		return &cloudgooglecomv1.NodeSystemConfigApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Placement"):
		return &cloudgooglecomv1.PlacementApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Priority"):
		return &cloudgooglecomv1.PriorityApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("PriorityDefaults"):
		return &cloudgooglecomv1.PriorityDefaultsApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ReservationBlock"):
		return &cloudgooglecomv1.ReservationBlockApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Reservations"):
		return &cloudgooglecomv1.ReservationsApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ReservationSubBlock"):
		return &cloudgooglecomv1.ReservationSubBlockApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("SecondaryBootDisk"):
		return &cloudgooglecomv1.SecondaryBootDiskApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("SpecificReservation"):
		return &cloudgooglecomv1.SpecificReservationApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Storage"):
		return &cloudgooglecomv1.StorageApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("SysctlsConfig"):
		return &cloudgooglecomv1.SysctlsConfigApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Tags"):
		return &cloudgooglecomv1.TagsApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("TaintConfig"):
		return &cloudgooglecomv1.TaintConfigApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("TopologyManager"):
		return &cloudgooglecomv1.TopologyManagerApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("TPU"):
		return &cloudgooglecomv1.TPUApplyConfiguration{}

	}
	return nil
}
