//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveMigration) DeepCopyInto(out *ActiveMigration) {
	*out = *in
	if in.EnsureAllDaemonSetPodsRunning != nil {
		in, out := &in.EnsureAllDaemonSetPodsRunning, &out.EnsureAllDaemonSetPodsRunning
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveMigration.
func (in *ActiveMigration) DeepCopy() *ActiveMigration {
	if in == nil {
		return nil
	}
	out := new(ActiveMigration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Autopilot) DeepCopyInto(out *Autopilot) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Autopilot.
func (in *Autopilot) DeepCopy() *Autopilot {
	if in == nil {
		return nil
	}
	out := new(Autopilot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicy) DeepCopyInto(out *AutoscalingPolicy) {
	*out = *in
	if in.ConsolidationDelayMinutes != nil {
		in, out := &in.ConsolidationDelayMinutes, &out.ConsolidationDelayMinutes
		*out = new(int)
		**out = **in
	}
	if in.ConsolidationThreshold != nil {
		in, out := &in.ConsolidationThreshold, &out.ConsolidationThreshold
		*out = new(int)
		**out = **in
	}
	if in.GPUConsolidationThreshold != nil {
		in, out := &in.GPUConsolidationThreshold, &out.GPUConsolidationThreshold
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicy.
func (in *AutoscalingPolicy) DeepCopy() *AutoscalingPolicy {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeClass) DeepCopyInto(out *ComputeClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeClass.
func (in *ComputeClass) DeepCopy() *ComputeClass {
	if in == nil {
		return nil
	}
	out := new(ComputeClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeClassList) DeepCopyInto(out *ComputeClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComputeClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeClassList.
func (in *ComputeClassList) DeepCopy() *ComputeClassList {
	if in == nil {
		return nil
	}
	out := new(ComputeClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeClassSpec) DeepCopyInto(out *ComputeClassSpec) {
	*out = *in
	if in.Priorities != nil {
		in, out := &in.Priorities, &out.Priorities
		*out = make([]Priority, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodePoolAutoCreation != nil {
		in, out := &in.NodePoolAutoCreation, &out.NodePoolAutoCreation
		*out = new(NodePoolAutoCreation)
		(*in).DeepCopyInto(*out)
	}
	if in.ActiveMigration != nil {
		in, out := &in.ActiveMigration, &out.ActiveMigration
		*out = new(ActiveMigration)
		(*in).DeepCopyInto(*out)
	}
	if in.AutoscalingPolicy != nil {
		in, out := &in.AutoscalingPolicy, &out.AutoscalingPolicy
		*out = new(AutoscalingPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Autopilot != nil {
		in, out := &in.Autopilot, &out.Autopilot
		*out = new(Autopilot)
		**out = **in
	}
	if in.NodePoolConfig != nil {
		in, out := &in.NodePoolConfig, &out.NodePoolConfig
		*out = new(NodePoolConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NodePoolGroup != nil {
		in, out := &in.NodePoolGroup, &out.NodePoolGroup
		*out = new(NodePoolGroup)
		**out = **in
	}
	if in.PriorityDefaults != nil {
		in, out := &in.PriorityDefaults, &out.PriorityDefaults
		*out = new(PriorityDefaults)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeClassSpec.
func (in *ComputeClassSpec) DeepCopy() *ComputeClassSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeClassStatus) DeepCopyInto(out *ComputeClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeClassStatus.
func (in *ComputeClassStatus) DeepCopy() *ComputeClassStatus {
	if in == nil {
		return nil
	}
	out := new(ComputeClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionMinimumReclaim) DeepCopyInto(out *EvictionMinimumReclaim) {
	*out = *in
	if in.MemoryAvailable != nil {
		in, out := &in.MemoryAvailable, &out.MemoryAvailable
		*out = new(string)
		**out = **in
	}
	if in.NodefsAvailable != nil {
		in, out := &in.NodefsAvailable, &out.NodefsAvailable
		*out = new(string)
		**out = **in
	}
	if in.ImagefsAvailable != nil {
		in, out := &in.ImagefsAvailable, &out.ImagefsAvailable
		*out = new(string)
		**out = **in
	}
	if in.ImagefsInodesFree != nil {
		in, out := &in.ImagefsInodesFree, &out.ImagefsInodesFree
		*out = new(string)
		**out = **in
	}
	if in.NodefsInodesFree != nil {
		in, out := &in.NodefsInodesFree, &out.NodefsInodesFree
		*out = new(string)
		**out = **in
	}
	if in.PidAvailable != nil {
		in, out := &in.PidAvailable, &out.PidAvailable
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionMinimumReclaim.
func (in *EvictionMinimumReclaim) DeepCopy() *EvictionMinimumReclaim {
	if in == nil {
		return nil
	}
	out := new(EvictionMinimumReclaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionSoft) DeepCopyInto(out *EvictionSoft) {
	*out = *in
	if in.MemoryAvailable != nil {
		in, out := &in.MemoryAvailable, &out.MemoryAvailable
		*out = new(string)
		**out = **in
	}
	if in.NodefsAvailable != nil {
		in, out := &in.NodefsAvailable, &out.NodefsAvailable
		*out = new(string)
		**out = **in
	}
	if in.ImagefsAvailable != nil {
		in, out := &in.ImagefsAvailable, &out.ImagefsAvailable
		*out = new(string)
		**out = **in
	}
	if in.ImagefsInodesFree != nil {
		in, out := &in.ImagefsInodesFree, &out.ImagefsInodesFree
		*out = new(string)
		**out = **in
	}
	if in.NodefsInodesFree != nil {
		in, out := &in.NodefsInodesFree, &out.NodefsInodesFree
		*out = new(string)
		**out = **in
	}
	if in.PidAvailable != nil {
		in, out := &in.PidAvailable, &out.PidAvailable
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionSoft.
func (in *EvictionSoft) DeepCopy() *EvictionSoft {
	if in == nil {
		return nil
	}
	out := new(EvictionSoft)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionSoftGracePeriod) DeepCopyInto(out *EvictionSoftGracePeriod) {
	*out = *in
	if in.MemoryAvailable != nil {
		in, out := &in.MemoryAvailable, &out.MemoryAvailable
		*out = new(string)
		**out = **in
	}
	if in.NodefsAvailable != nil {
		in, out := &in.NodefsAvailable, &out.NodefsAvailable
		*out = new(string)
		**out = **in
	}
	if in.ImagefsAvailable != nil {
		in, out := &in.ImagefsAvailable, &out.ImagefsAvailable
		*out = new(string)
		**out = **in
	}
	if in.ImagefsInodesFree != nil {
		in, out := &in.ImagefsInodesFree, &out.ImagefsInodesFree
		*out = new(string)
		**out = **in
	}
	if in.NodefsInodesFree != nil {
		in, out := &in.NodefsInodesFree, &out.NodefsInodesFree
		*out = new(string)
		**out = **in
	}
	if in.PidAvailable != nil {
		in, out := &in.PidAvailable, &out.PidAvailable
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionSoftGracePeriod.
func (in *EvictionSoftGracePeriod) DeepCopy() *EvictionSoftGracePeriod {
	if in == nil {
		return nil
	}
	out := new(EvictionSoftGracePeriod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlexStart) DeepCopyInto(out *FlexStart) {
	*out = *in
	if in.NodeRecycling != nil {
		in, out := &in.NodeRecycling, &out.NodeRecycling
		*out = new(NodeRecyclingConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlexStart.
func (in *FlexStart) DeepCopy() *FlexStart {
	if in == nil {
		return nil
	}
	out := new(FlexStart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPU) DeepCopyInto(out *GPU) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPU.
func (in *GPU) DeepCopy() *GPU {
	if in == nil {
		return nil
	}
	out := new(GPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HugepagesConfig) DeepCopyInto(out *HugepagesConfig) {
	*out = *in
	if in.HugepageSize1g != nil {
		in, out := &in.HugepageSize1g, &out.HugepageSize1g
		*out = new(int64)
		**out = **in
	}
	if in.HugepageSize2m != nil {
		in, out := &in.HugepageSize2m, &out.HugepageSize2m
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HugepagesConfig.
func (in *HugepagesConfig) DeepCopy() *HugepagesConfig {
	if in == nil {
		return nil
	}
	out := new(HugepagesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageStreaming) DeepCopyInto(out *ImageStreaming) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageStreaming.
func (in *ImageStreaming) DeepCopy() *ImageStreaming {
	if in == nil {
		return nil
	}
	out := new(ImageStreaming)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeletConfig) DeepCopyInto(out *KubeletConfig) {
	*out = *in
	if in.CpuCfsQuota != nil {
		in, out := &in.CpuCfsQuota, &out.CpuCfsQuota
		*out = new(bool)
		**out = **in
	}
	if in.CpuCfsQuotaPeriod != nil {
		in, out := &in.CpuCfsQuotaPeriod, &out.CpuCfsQuotaPeriod
		*out = new(string)
		**out = **in
	}
	if in.CpuManagerPolicy != nil {
		in, out := &in.CpuManagerPolicy, &out.CpuManagerPolicy
		*out = new(string)
		**out = **in
	}
	if in.PodPidsLimit != nil {
		in, out := &in.PodPidsLimit, &out.PodPidsLimit
		*out = new(int64)
		**out = **in
	}
	if in.ImageGcLowThresholdPercent != nil {
		in, out := &in.ImageGcLowThresholdPercent, &out.ImageGcLowThresholdPercent
		*out = new(int64)
		**out = **in
	}
	if in.ImageGcHighThresholdPercent != nil {
		in, out := &in.ImageGcHighThresholdPercent, &out.ImageGcHighThresholdPercent
		*out = new(int64)
		**out = **in
	}
	if in.ImageMinimumGcAge != nil {
		in, out := &in.ImageMinimumGcAge, &out.ImageMinimumGcAge
		*out = new(string)
		**out = **in
	}
	if in.ImageMaximumGcAge != nil {
		in, out := &in.ImageMaximumGcAge, &out.ImageMaximumGcAge
		*out = new(string)
		**out = **in
	}
	if in.ContainerLogMaxSize != nil {
		in, out := &in.ContainerLogMaxSize, &out.ContainerLogMaxSize
		*out = new(string)
		**out = **in
	}
	if in.ContainerLogMaxFiles != nil {
		in, out := &in.ContainerLogMaxFiles, &out.ContainerLogMaxFiles
		*out = new(int64)
		**out = **in
	}
	if in.AllowedUnsafeSysctls != nil {
		in, out := &in.AllowedUnsafeSysctls, &out.AllowedUnsafeSysctls
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxParallelImagePulls != nil {
		in, out := &in.MaxParallelImagePulls, &out.MaxParallelImagePulls
		*out = new(int64)
		**out = **in
	}
	if in.SingleProcessOOMKill != nil {
		in, out := &in.SingleProcessOOMKill, &out.SingleProcessOOMKill
		*out = new(bool)
		**out = **in
	}
	if in.EvictionSoft != nil {
		in, out := &in.EvictionSoft, &out.EvictionSoft
		*out = new(EvictionSoft)
		(*in).DeepCopyInto(*out)
	}
	if in.EvictionSoftGracePeriod != nil {
		in, out := &in.EvictionSoftGracePeriod, &out.EvictionSoftGracePeriod
		*out = new(EvictionSoftGracePeriod)
		(*in).DeepCopyInto(*out)
	}
	if in.EvictionMinimumReclaim != nil {
		in, out := &in.EvictionMinimumReclaim, &out.EvictionMinimumReclaim
		*out = new(EvictionMinimumReclaim)
		(*in).DeepCopyInto(*out)
	}
	if in.EvictionMaxPodGracePeriodSeconds != nil {
		in, out := &in.EvictionMaxPodGracePeriodSeconds, &out.EvictionMaxPodGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeletConfig.
func (in *KubeletConfig) DeepCopy() *KubeletConfig {
	if in == nil {
		return nil
	}
	out := new(KubeletConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinuxNodeConfig) DeepCopyInto(out *LinuxNodeConfig) {
	*out = *in
	if in.Sysctls != nil {
		in, out := &in.Sysctls, &out.Sysctls
		*out = new(SysctlsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Hugepages != nil {
		in, out := &in.Hugepages, &out.Hugepages
		*out = new(HugepagesConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TransparentHugepageEnabled != nil {
		in, out := &in.TransparentHugepageEnabled, &out.TransparentHugepageEnabled
		*out = new(string)
		**out = **in
	}
	if in.TransparentHugepageDefrag != nil {
		in, out := &in.TransparentHugepageDefrag, &out.TransparentHugepageDefrag
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinuxNodeConfig.
func (in *LinuxNodeConfig) DeepCopy() *LinuxNodeConfig {
	if in == nil {
		return nil
	}
	out := new(LinuxNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Location) DeepCopyInto(out *Location) {
	*out = *in
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LocationPolicy != nil {
		in, out := &in.LocationPolicy, &out.LocationPolicy
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Location.
func (in *Location) DeepCopy() *Location {
	if in == nil {
		return nil
	}
	out := new(Location)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolAutoCreation) DeepCopyInto(out *NodePoolAutoCreation) {
	*out = *in
	if in.DynamicMaxPodsPerNode != nil {
		in, out := &in.DynamicMaxPodsPerNode, &out.DynamicMaxPodsPerNode
		*out = new(bool)
		**out = **in
	}
	if in.DynamicBootDiskSize != nil {
		in, out := &in.DynamicBootDiskSize, &out.DynamicBootDiskSize
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolAutoCreation.
func (in *NodePoolAutoCreation) DeepCopy() *NodePoolAutoCreation {
	if in == nil {
		return nil
	}
	out := new(NodePoolAutoCreation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolConfig) DeepCopyInto(out *NodePoolConfig) {
	*out = *in
	if in.NodeLabels != nil {
		in, out := &in.NodeLabels, &out.NodeLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]TaintConfig, len(*in))
		copy(*out, *in)
	}
	if in.AutoRepair != nil {
		in, out := &in.AutoRepair, &out.AutoRepair
		*out = new(bool)
		**out = **in
	}
	if in.AutoUpgrade != nil {
		in, out := &in.AutoUpgrade, &out.AutoUpgrade
		*out = new(bool)
		**out = **in
	}
	if in.ImageStreaming != nil {
		in, out := &in.ImageStreaming, &out.ImageStreaming
		*out = new(ImageStreaming)
		**out = **in
	}
	if in.ResourceManagerTags != nil {
		in, out := &in.ResourceManagerTags, &out.ResourceManagerTags
		*out = make([]Tags, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolConfig.
func (in *NodePoolConfig) DeepCopy() *NodePoolConfig {
	if in == nil {
		return nil
	}
	out := new(NodePoolConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolGroup) DeepCopyInto(out *NodePoolGroup) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolGroup.
func (in *NodePoolGroup) DeepCopy() *NodePoolGroup {
	if in == nil {
		return nil
	}
	out := new(NodePoolGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRecyclingConfig) DeepCopyInto(out *NodeRecyclingConfig) {
	*out = *in
	if in.LeadTimeSeconds != nil {
		in, out := &in.LeadTimeSeconds, &out.LeadTimeSeconds
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRecyclingConfig.
func (in *NodeRecyclingConfig) DeepCopy() *NodeRecyclingConfig {
	if in == nil {
		return nil
	}
	out := new(NodeRecyclingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSystemConfig) DeepCopyInto(out *NodeSystemConfig) {
	*out = *in
	if in.LinuxNodeConfig != nil {
		in, out := &in.LinuxNodeConfig, &out.LinuxNodeConfig
		*out = new(LinuxNodeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.KubeletConfig != nil {
		in, out := &in.KubeletConfig, &out.KubeletConfig
		*out = new(KubeletConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSystemConfig.
func (in *NodeSystemConfig) DeepCopy() *NodeSystemConfig {
	if in == nil {
		return nil
	}
	out := new(NodeSystemConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Placement) DeepCopyInto(out *Placement) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Placement.
func (in *Placement) DeepCopy() *Placement {
	if in == nil {
		return nil
	}
	out := new(Placement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Priority) DeepCopyInto(out *Priority) {
	*out = *in
	if in.MachineFamily != nil {
		in, out := &in.MachineFamily, &out.MachineFamily
		*out = new(string)
		**out = **in
	}
	if in.Spot != nil {
		in, out := &in.Spot, &out.Spot
		*out = new(bool)
		**out = **in
	}
	if in.MinCores != nil {
		in, out := &in.MinCores, &out.MinCores
		*out = new(int)
		**out = **in
	}
	if in.MinMemoryGb != nil {
		in, out := &in.MinMemoryGb, &out.MinMemoryGb
		*out = new(int)
		**out = **in
	}
	if in.Nodepools != nil {
		in, out := &in.Nodepools, &out.Nodepools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(Storage)
		(*in).DeepCopyInto(*out)
	}
	if in.MachineType != nil {
		in, out := &in.MachineType, &out.MachineType
		*out = new(string)
		**out = **in
	}
	if in.Gpu != nil {
		in, out := &in.Gpu, &out.Gpu
		*out = new(GPU)
		**out = **in
	}
	if in.Tpu != nil {
		in, out := &in.Tpu, &out.Tpu
		*out = new(TPU)
		**out = **in
	}
	if in.Reservations != nil {
		in, out := &in.Reservations, &out.Reservations
		*out = new(Reservations)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxRunDurationSeconds != nil {
		in, out := &in.MaxRunDurationSeconds, &out.MaxRunDurationSeconds
		*out = new(int)
		**out = **in
	}
	if in.MaxPodsPerNode != nil {
		in, out := &in.MaxPodsPerNode, &out.MaxPodsPerNode
		*out = new(int)
		**out = **in
	}
	if in.NodeSystemConfig != nil {
		in, out := &in.NodeSystemConfig, &out.NodeSystemConfig
		*out = new(NodeSystemConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.FlexStart != nil {
		in, out := &in.FlexStart, &out.FlexStart
		*out = new(FlexStart)
		(*in).DeepCopyInto(*out)
	}
	if in.PodFamily != nil {
		in, out := &in.PodFamily, &out.PodFamily
		*out = new(string)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(Location)
		(*in).DeepCopyInto(*out)
	}
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(Placement)
		**out = **in
	}
	if in.CapacityCheckWaitTimeSeconds != nil {
		in, out := &in.CapacityCheckWaitTimeSeconds, &out.CapacityCheckWaitTimeSeconds
		*out = new(int)
		**out = **in
	}
	if in.MinCpuPlatform != nil {
		in, out := &in.MinCpuPlatform, &out.MinCpuPlatform
		*out = new(string)
		**out = **in
	}
	if in.NodeLabels != nil {
		in, out := &in.NodeLabels, &out.NodeLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]TaintConfig, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Priority.
func (in *Priority) DeepCopy() *Priority {
	if in == nil {
		return nil
	}
	out := new(Priority)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriorityDefaults) DeepCopyInto(out *PriorityDefaults) {
	*out = *in
	if in.NodeSystemConfig != nil {
		in, out := &in.NodeSystemConfig, &out.NodeSystemConfig
		*out = new(NodeSystemConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(Location)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriorityDefaults.
func (in *PriorityDefaults) DeepCopy() *PriorityDefaults {
	if in == nil {
		return nil
	}
	out := new(PriorityDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationBlock) DeepCopyInto(out *ReservationBlock) {
	*out = *in
	if in.ReservationSubBlock != nil {
		in, out := &in.ReservationSubBlock, &out.ReservationSubBlock
		*out = new(ReservationSubBlock)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationBlock.
func (in *ReservationBlock) DeepCopy() *ReservationBlock {
	if in == nil {
		return nil
	}
	out := new(ReservationBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationSubBlock) DeepCopyInto(out *ReservationSubBlock) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationSubBlock.
func (in *ReservationSubBlock) DeepCopy() *ReservationSubBlock {
	if in == nil {
		return nil
	}
	out := new(ReservationSubBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Reservations) DeepCopyInto(out *Reservations) {
	*out = *in
	if in.Specific != nil {
		in, out := &in.Specific, &out.Specific
		*out = make([]SpecificReservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Reservations.
func (in *Reservations) DeepCopy() *Reservations {
	if in == nil {
		return nil
	}
	out := new(Reservations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecondaryBootDisk) DeepCopyInto(out *SecondaryBootDisk) {
	*out = *in
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecondaryBootDisk.
func (in *SecondaryBootDisk) DeepCopy() *SecondaryBootDisk {
	if in == nil {
		return nil
	}
	out := new(SecondaryBootDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecificReservation) DeepCopyInto(out *SpecificReservation) {
	*out = *in
	if in.ReservationBlock != nil {
		in, out := &in.ReservationBlock, &out.ReservationBlock
		*out = new(ReservationBlock)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecificReservation.
func (in *SpecificReservation) DeepCopy() *SpecificReservation {
	if in == nil {
		return nil
	}
	out := new(SpecificReservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Storage) DeepCopyInto(out *Storage) {
	*out = *in
	if in.BootDiskSize != nil {
		in, out := &in.BootDiskSize, &out.BootDiskSize
		*out = new(int)
		**out = **in
	}
	if in.BootDiskType != nil {
		in, out := &in.BootDiskType, &out.BootDiskType
		*out = new(string)
		**out = **in
	}
	if in.BootDiskKMSKey != nil {
		in, out := &in.BootDiskKMSKey, &out.BootDiskKMSKey
		*out = new(string)
		**out = **in
	}
	if in.LocalSSDCount != nil {
		in, out := &in.LocalSSDCount, &out.LocalSSDCount
		*out = new(int)
		**out = **in
	}
	if in.SecondaryBootDisks != nil {
		in, out := &in.SecondaryBootDisks, &out.SecondaryBootDisks
		*out = make([]SecondaryBootDisk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Storage.
func (in *Storage) DeepCopy() *Storage {
	if in == nil {
		return nil
	}
	out := new(Storage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SysctlsConfig) DeepCopyInto(out *SysctlsConfig) {
	*out = *in
	if in.Net_core_netdev_max_backlog != nil {
		in, out := &in.Net_core_netdev_max_backlog, &out.Net_core_netdev_max_backlog
		*out = new(int64)
		**out = **in
	}
	if in.Net_core_rmem_max != nil {
		in, out := &in.Net_core_rmem_max, &out.Net_core_rmem_max
		*out = new(int64)
		**out = **in
	}
	if in.Net_core_wmem_default != nil {
		in, out := &in.Net_core_wmem_default, &out.Net_core_wmem_default
		*out = new(int64)
		**out = **in
	}
	if in.Net_core_wmem_max != nil {
		in, out := &in.Net_core_wmem_max, &out.Net_core_wmem_max
		*out = new(int64)
		**out = **in
	}
	if in.Net_core_optmem_max != nil {
		in, out := &in.Net_core_optmem_max, &out.Net_core_optmem_max
		*out = new(int64)
		**out = **in
	}
	if in.Net_core_somaxconn != nil {
		in, out := &in.Net_core_somaxconn, &out.Net_core_somaxconn
		*out = new(int64)
		**out = **in
	}
	if in.Net_ipv4_tcp_rmem != nil {
		in, out := &in.Net_ipv4_tcp_rmem, &out.Net_ipv4_tcp_rmem
		*out = new(string)
		**out = **in
	}
	if in.Net_ipv4_tcp_wmem != nil {
		in, out := &in.Net_ipv4_tcp_wmem, &out.Net_ipv4_tcp_wmem
		*out = new(string)
		**out = **in
	}
	if in.Net_ipv4_tcp_tw_reuse != nil {
		in, out := &in.Net_ipv4_tcp_tw_reuse, &out.Net_ipv4_tcp_tw_reuse
		*out = new(int64)
		**out = **in
	}
	if in.Net_core_busy_poll != nil {
		in, out := &in.Net_core_busy_poll, &out.Net_core_busy_poll
		*out = new(int64)
		**out = **in
	}
	if in.Net_core_busy_read != nil {
		in, out := &in.Net_core_busy_read, &out.Net_core_busy_read
		*out = new(int64)
		**out = **in
	}
	if in.Net_ipv6_conf_all_disable_ipv6 != nil {
		in, out := &in.Net_ipv6_conf_all_disable_ipv6, &out.Net_ipv6_conf_all_disable_ipv6
		*out = new(bool)
		**out = **in
	}
	if in.Net_ipv6_conf_default_disable_ipv6 != nil {
		in, out := &in.Net_ipv6_conf_default_disable_ipv6, &out.Net_ipv6_conf_default_disable_ipv6
		*out = new(bool)
		**out = **in
	}
	if in.Vm_max_map_count != nil {
		in, out := &in.Vm_max_map_count, &out.Vm_max_map_count
		*out = new(int64)
		**out = **in
	}
	if in.Kernel_shmmni != nil {
		in, out := &in.Kernel_shmmni, &out.Kernel_shmmni
		*out = new(int64)
		**out = **in
	}
	if in.Kernel_shmall != nil {
		in, out := &in.Kernel_shmall, &out.Kernel_shmall
		*out = new(string)
		**out = **in
	}
	if in.Kernel_shmmax != nil {
		in, out := &in.Kernel_shmmax, &out.Kernel_shmmax
		*out = new(string)
		**out = **in
	}
	if in.Net_core_rmem_default != nil {
		in, out := &in.Net_core_rmem_default, &out.Net_core_rmem_default
		*out = new(int64)
		**out = **in
	}
	if in.Net_netfilter_nf_conntrack_max != nil {
		in, out := &in.Net_netfilter_nf_conntrack_max, &out.Net_netfilter_nf_conntrack_max
		*out = new(int64)
		**out = **in
	}
	if in.Net_netfilter_nf_conntrack_buckets != nil {
		in, out := &in.Net_netfilter_nf_conntrack_buckets, &out.Net_netfilter_nf_conntrack_buckets
		*out = new(int64)
		**out = **in
	}
	if in.Net_netfilter_nf_conntrack_acct != nil {
		in, out := &in.Net_netfilter_nf_conntrack_acct, &out.Net_netfilter_nf_conntrack_acct
		*out = new(bool)
		**out = **in
	}
	if in.Net_netfilter_nf_conntrack_tcp_timeout_established != nil {
		in, out := &in.Net_netfilter_nf_conntrack_tcp_timeout_established, &out.Net_netfilter_nf_conntrack_tcp_timeout_established
		*out = new(int64)
		**out = **in
	}
	if in.Net_netfilter_nf_conntrack_tcp_timeout_close_wait != nil {
		in, out := &in.Net_netfilter_nf_conntrack_tcp_timeout_close_wait, &out.Net_netfilter_nf_conntrack_tcp_timeout_close_wait
		*out = new(int64)
		**out = **in
	}
	if in.Net_netfilter_nf_conntrack_tcp_timeout_time_wait != nil {
		in, out := &in.Net_netfilter_nf_conntrack_tcp_timeout_time_wait, &out.Net_netfilter_nf_conntrack_tcp_timeout_time_wait
		*out = new(int64)
		**out = **in
	}
	if in.Fs_nr_open != nil {
		in, out := &in.Fs_nr_open, &out.Fs_nr_open
		*out = new(int64)
		**out = **in
	}
	if in.Fs_inotify_max_user_watches != nil {
		in, out := &in.Fs_inotify_max_user_watches, &out.Fs_inotify_max_user_watches
		*out = new(int64)
		**out = **in
	}
	if in.Fs_inotify_max_user_instances != nil {
		in, out := &in.Fs_inotify_max_user_instances, &out.Fs_inotify_max_user_instances
		*out = new(int64)
		**out = **in
	}
	if in.Vm_overcommit_memory != nil {
		in, out := &in.Vm_overcommit_memory, &out.Vm_overcommit_memory
		*out = new(int64)
		**out = **in
	}
	if in.Vm_overcommit_ratio != nil {
		in, out := &in.Vm_overcommit_ratio, &out.Vm_overcommit_ratio
		*out = new(int64)
		**out = **in
	}
	if in.Vm_vfs_cache_pressure != nil {
		in, out := &in.Vm_vfs_cache_pressure, &out.Vm_vfs_cache_pressure
		*out = new(int64)
		**out = **in
	}
	if in.Vm_dirty_background_ratio != nil {
		in, out := &in.Vm_dirty_background_ratio, &out.Vm_dirty_background_ratio
		*out = new(int64)
		**out = **in
	}
	if in.Vm_dirty_ratio != nil {
		in, out := &in.Vm_dirty_ratio, &out.Vm_dirty_ratio
		*out = new(int64)
		**out = **in
	}
	if in.Vm_dirty_expire_centisecs != nil {
		in, out := &in.Vm_dirty_expire_centisecs, &out.Vm_dirty_expire_centisecs
		*out = new(int64)
		**out = **in
	}
	if in.Vm_dirty_writeback_centisecs != nil {
		in, out := &in.Vm_dirty_writeback_centisecs, &out.Vm_dirty_writeback_centisecs
		*out = new(int64)
		**out = **in
	}
	if in.Fs_file_max != nil {
		in, out := &in.Fs_file_max, &out.Fs_file_max
		*out = new(int64)
		**out = **in
	}
	if in.Fs_aio_max_nr != nil {
		in, out := &in.Fs_aio_max_nr, &out.Fs_aio_max_nr
		*out = new(int64)
		**out = **in
	}
	if in.Net_ipv4_tcp_max_orphans != nil {
		in, out := &in.Net_ipv4_tcp_max_orphans, &out.Net_ipv4_tcp_max_orphans
		*out = new(int64)
		**out = **in
	}
	if in.Vm_swappiness != nil {
		in, out := &in.Vm_swappiness, &out.Vm_swappiness
		*out = new(int64)
		**out = **in
	}
	if in.Vm_watermark_scale_factor != nil {
		in, out := &in.Vm_watermark_scale_factor, &out.Vm_watermark_scale_factor
		*out = new(int64)
		**out = **in
	}
	if in.Vm_min_free_kbytes != nil {
		in, out := &in.Vm_min_free_kbytes, &out.Vm_min_free_kbytes
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SysctlsConfig.
func (in *SysctlsConfig) DeepCopy() *SysctlsConfig {
	if in == nil {
		return nil
	}
	out := new(SysctlsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TPU) DeepCopyInto(out *TPU) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TPU.
func (in *TPU) DeepCopy() *TPU {
	if in == nil {
		return nil
	}
	out := new(TPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tags) DeepCopyInto(out *Tags) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tags.
func (in *Tags) DeepCopy() *Tags {
	if in == nil {
		return nil
	}
	out := new(Tags)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaintConfig) DeepCopyInto(out *TaintConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaintConfig.
func (in *TaintConfig) DeepCopy() *TaintConfig {
	if in == nil {
		return nil
	}
	out := new(TaintConfig)
	in.DeepCopyInto(out)
	return out
}
