//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveMigration) DeepCopyInto(out *ActiveMigration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveMigration.
func (in *ActiveMigration) DeepCopy() *ActiveMigration {
	if in == nil {
		return nil
	}
	out := new(ActiveMigration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeClass) DeepCopyInto(out *ComputeClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeClass.
func (in *ComputeClass) DeepCopy() *ComputeClass {
	if in == nil {
		return nil
	}
	out := new(ComputeClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeClassList) DeepCopyInto(out *ComputeClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComputeClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeClassList.
func (in *ComputeClassList) DeepCopy() *ComputeClassList {
	if in == nil {
		return nil
	}
	out := new(ComputeClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeClassSpec) DeepCopyInto(out *ComputeClassSpec) {
	*out = *in
	if in.Priorities != nil {
		in, out := &in.Priorities, &out.Priorities
		*out = make([]Priority, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodePoolAutoCreation != nil {
		in, out := &in.NodePoolAutoCreation, &out.NodePoolAutoCreation
		*out = new(NodePoolAutoCreation)
		**out = **in
	}
	if in.ActiveMigration != nil {
		in, out := &in.ActiveMigration, &out.ActiveMigration
		*out = new(ActiveMigration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeClassSpec.
func (in *ComputeClassSpec) DeepCopy() *ComputeClassSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeClassStatus) DeepCopyInto(out *ComputeClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeClassStatus.
func (in *ComputeClassStatus) DeepCopy() *ComputeClassStatus {
	if in == nil {
		return nil
	}
	out := new(ComputeClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolAutoCreation) DeepCopyInto(out *NodePoolAutoCreation) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolAutoCreation.
func (in *NodePoolAutoCreation) DeepCopy() *NodePoolAutoCreation {
	if in == nil {
		return nil
	}
	out := new(NodePoolAutoCreation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Priority) DeepCopyInto(out *Priority) {
	*out = *in
	if in.MachineFamily != nil {
		in, out := &in.MachineFamily, &out.MachineFamily
		*out = new(string)
		**out = **in
	}
	if in.Spot != nil {
		in, out := &in.Spot, &out.Spot
		*out = new(bool)
		**out = **in
	}
	if in.MinCores != nil {
		in, out := &in.MinCores, &out.MinCores
		*out = new(int)
		**out = **in
	}
	if in.MinMemoryGb != nil {
		in, out := &in.MinMemoryGb, &out.MinMemoryGb
		*out = new(int)
		**out = **in
	}
	if in.Nodepools != nil {
		in, out := &in.Nodepools, &out.Nodepools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Priority.
func (in *Priority) DeepCopy() *Priority {
	if in == nil {
		return nil
	}
	out := new(Priority)
	in.DeepCopyInto(out)
	return out
}
