/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	cloudgooglecomv1 "github.com/googlecloudplatform/compute-class-api/api/cloud.google.com/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ComputeClassLister helps list ComputeClasses.
// All objects returned here must be treated as read-only.
type ComputeClassLister interface {
	// List lists all ComputeClasses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*cloudgooglecomv1.ComputeClass, err error)
	// Get retrieves the ComputeClass from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*cloudgooglecomv1.ComputeClass, error)
	ComputeClassListerExpansion
}

// computeClassLister implements the ComputeClassLister interface.
type computeClassLister struct {
	listers.ResourceIndexer[*cloudgooglecomv1.ComputeClass]
}

// NewComputeClassLister returns a new ComputeClassLister.
func NewComputeClassLister(indexer cache.Indexer) ComputeClassLister {
	return &computeClassLister{listers.New[*cloudgooglecomv1.ComputeClass](indexer, cloudgooglecomv1.Resource("computeclass"))}
}
